Use pnetput instead of some weird mk.xml script. Clean up Makefile and parsu_tracebytrace.in. Fix last commit which had <in port instead of <in name.

diff --git a/application/parsu/tracebytrace/parsu_tracebytrace.in b/application/parsu/tracebytrace/parsu_tracebytrace.in
--- a/application/parsu/tracebytrace/parsu_tracebytrace.in
+++ b/application/parsu/tracebytrace/parsu_tracebytrace.in
@@ -14,7 +14,6 @@ scratch_dir="$HOME/.sdpa/scratch"
 test ! -d "${scratch_dir}" && { mkdir -p "${scratch_dir}" ; }
 
 xml_file_in="${tracebytrace_dir}/tracebytrace.xml.in"
-mk_xml="${tracebytrace_dir}/mk.xml"
 
 skipped_traces_default=0
 max_trace_count_default=-1
@@ -43,19 +42,26 @@ if [ ! -r "$inf" ] ; then
 fi
 
 if [ -e "$outf" ] ; then
-    echo "W: deleting old output file" >/dev/stderr
-    rm "$outf"
+  echo "W: deleting old output file" >/dev/stderr
+  rm "$outf"
 fi
 
 cleanup ()
 {
-    test -e "${xml_file}"  && rm -f "${xml_file}"
-    test -e "${pnet_file}" && rm -f "${pnet_file}"
-    test -e "${script_file}" && rm -f "${script_file}"
+  test -e "${xml_file}"  && rm -f "${xml_file}"
+  test -e "${pnet_file_in}" && rm -f "${pnet_file_in}"
+  test -e "${pnet_file}" && rm -f "${pnet_file}"
+  test -e "${script_file}" && rm -f "${script_file}"
 }
 trap cleanup EXIT
 
 xml_file=$( mktemp "${tmp_dir}/parsu_tracebytrace.xml.XXXXXX" )
+if [ $? -ne 0 ] ; then
+  echo "could not create temporary file in ${tmp_dir}" >/dev/stderr
+  exit 2
+fi
+
+pnet_file_in=$( mktemp "${tmp_dir}/parsu_tracebytrace.pnet.in.XXXXXX" )
 if [ $? -ne 0 ] ; then
   echo "could not create temporary file in ${tmp_dir}" >/dev/stderr
   exit 2
@@ -69,8 +75,8 @@ fi
 
 script_file=$( mktemp "${scratch_dir}/parsu_tracebytrace.sh.XXXXXX" )
 if [ $? -ne 0 ] ; then
-    echo "could not create temporary script in ${scratch_dir}" >&2
-    exit 2
+  echo "could not create temporary script in ${scratch_dir}" >/dev/stderr
+  exit 2
 fi
 chmod +x "${script_file}"
 
@@ -94,26 +100,11 @@ abs_inf="$REPLY"
 abspath ${outf}
 abs_outf="$REPLY"
 
-echo "-: generating command script..." >&2
+echo -n "-: generating command script... " >/dev/stderr
 cat > "$script_file" <<EOF
 #!/bin/sh
 exec $cmd
 EOF
-
-echo -n "-: generating job description..." >/dev/stderr
-
-cat "${xml_file_in}" | ${mk_xml}             \
-                       "${abs_inf}"          \
-                       "${int}"              \
-                       "${abs_outf}"         \
-                       "${outt}"             \
-                       "${script_file}"      \
-                       "${skipped_traces}"   \
-                       "${max_trace_count}"  \
-                       "${shmem_per_node}"   \
-                       "${gpi_mem_per_node}" \
-                       "--BUILD--"           \
-                     > "${xml_file}"
 
 if [ $? -ne 0 ] ; then
   echo "E: generating failed!" >/dev/stderr
@@ -121,5 +112,49 @@ if [ $? -ne 0 ] ; then
 fi
 echo "ok" >/dev/stderr
 
-PARSU_PNETC_LIB_DIR="${tracebytrace_dir} -I @PARSU_PNETC_LIB_DIR@" \
-parsu_run "${xml_file}" "${pnet_file}"
+echo -n "-: compiling job description... " >/dev/stderr
+pnetc ${xml_file_in}                        \
+      -I "${tracebytrace_dir}"              \
+      -I "${SDPA_HOME}/share/sdpa/xml/lib"  \
+      > ${pnet_file_in}
+
+if [ $? -ne 0 ] ; then
+  echo "E: generating failed!" >/dev/stderr
+  exit 2
+fi
+echo "ok" >/dev/stderr
+
+echo -n "-: putting parameters on input places... " >/dev/stderr
+pnetput -p "cmd=\"${script_file}\""                 \
+        -p "file_input=\"${abs_inf}\""              \
+        -p "file_output=\"${abs_outf}\""            \
+        -p "type_input=\"${int}\""                  \
+        -p "type_output=\"${outt}\""                \
+        -p "skipped_traces=${skipped_traces}"       \
+        -p "maximum_trace_count=${max_trace_count}" \
+        -p "shmem_per_node=${shmem_per_node}"       \
+        -p "gpi_mem_per_node=${gpi_mem_per_node}"   \
+        < ${pnet_file_in} > ${pnet_file}
+
+if [ $? -ne 0 ] ; then
+  echo "E: generating failed!" >/dev/stderr
+  exit 2
+fi
+echo "ok" >/dev/stderr
+
+jobid=$( sdpac submit ${pnet_file} 2>&1 )
+ec=$?
+if [ $ec -ne 0 ] ; then
+  echo "Could not submit job: $jobid" >/dev/stderr
+  exit $ec
+fi
+echo "JOB-ID := $jobid"
+sdpac wait "$jobid"
+ec=$?
+if [ $ec -ne 0 ] ; then
+  echo "Job execution failed: $ec" >/dev/stderr
+else
+  echo "Success."
+fi
+sdpac delete "$jobid"
+exit $ec
