build: chg: send mails not via trap

diff --git a/gitlab-ci-build b/gitlab-ci-build
--- a/gitlab-ci-build
+++ b/gitlab-ci-build
@@ -39,28 +39,31 @@ case "$myhost" in
         ;;
 esac
 
-do_send_mail ()
+log_and_maybe_send_mail ()
 {
+    local ec="$1" ; shift
+
     if [ $ec -eq 0 ]
     then
-        state="SUCCESS"
+        msg="${@}"
     else
-        state="FAILED"
+        msg="${@} (ec=$ec)"
     fi
     sha=$(git rev-parse --short HEAD)
-    mail -s "[CI] build of ${sha}: ${state}" -r "Gitlab-CI <sdpa-dev@itwm.fhg.de>" "${to}" </dev/null
-}
 
-if $send_mail
-then
-    trap do_send_mail EXIT
-fi
+    echo >&2 "${msg}"
+
+    if $send_mail
+    then
+        mail -s "[CI] build of ${sha}: ${msg}" -r "Gitlab-CI <sdpa-dev@itwm.fhg.de>" "${to}" </dev/null
+    fi
+}
 
 ./configure --prefix=$PWD/inst "${opts[@]}"
 ec=$?
 if [ $ec -ne 0 ]
 then
-    echo >&2 "CONFIGURE FAILED: ec=$ec"
+    log_and_maybe_send_mail $ec "CONFIGURE FAILED"
     exit $ec
 fi
 
@@ -68,7 +71,7 @@ make "${makeflags[@]}"
 ec=$?
 if [ $ec -ne 0 ]
 then
-    echo >&2 "MAKE FAILED: ec=$ec"
+    log_and_maybe_send_mail $ec "MAKE FAILED"
     exit $ec
 fi
 
@@ -76,7 +79,7 @@ make "${makeflags[@]}" install
 ec=$?
 if [ $ec -ne 0 ]
 then
-    echo >&2 "INSTALL FAILED: ec=$ec"
+    log_and_maybe_send_mail $ec "INSTALL FAILED"
     exit $ec
 fi
 
@@ -86,9 +89,9 @@ then
     ec=$?
     if [ $ec -ne 0 ]
     then
-        echo >&2 "TESTS FAILED: ec=$ec"
+        log_and_maybe_send_mail $ec "TESTS FAILED"
         exit $ec
     fi
 fi
 
-exit 0
+log_and_maybe_send_mail 0 "SUCCESS"
