build: new: added timeout of 360s to ctest

diff --git a/gspc-build b/gspc-build
--- a/gspc-build
+++ b/gspc-build
@@ -104,7 +104,7 @@ echo "$(date)" > "${builddir}/build.tstamp"
 
 make -j "${jobs}" || { echo >&2 "FAILED: could not BUILD" ; exit 12; }
 if $execute_tests ; then
-  ctest -j "${jobs}" || { echo >&2 "WARN: could not TEST" ; }
+  ctest -j "${jobs}" --timeout 360 || { echo >&2 "WARN: could not TEST" ; }
 fi
 
 if [ -d "${instdir}" ] ; then
