do not cancel if submission failed
From: Alexander Petry <alexander.petry@itwm.fraunhofer.de>

git-svn-id: https://svn.itwm.fhg.de/svn/SDPA@6687 c3adf61f-8968-0410-94d0-83abfdf586cf

diff --git a/trunk/application/cc/sdpacc b/trunk/application/cc/sdpacc
--- a/trunk/application/cc/sdpacc
+++ b/trunk/application/cc/sdpacc
@@ -104,12 +104,13 @@ function prepare ()
 
 function execute ()
 {
-    jobid=$(sdpac $SDPACFLAGS submit ${pnet_tmp} 2>&1)
+    jobid_or_err=$(sdpac $SDPACFLAGS submit ${pnet_tmp} 2>&1)
     ec=$?
     if [ $ec -ne 0 ] ; then
-	echo "submission failed: $jobid" >&2
+	echo "submission failed: $jobid_or_err" >&2
 	return $ec
     fi
+    jobid="$jobid_or_err"
     test -e "${pnet_tmp}" && rm -f "${pnet_tmp}"
     sdpac $SDPACFLAGS wait "$jobid" &>/dev/null
     ec=$?
