env: chg: figure out where SDPA_HOME, if possible

diff --git a/sdpa/etc/sdpa.env.in b/sdpa/etc/sdpa.env.in
--- a/sdpa/etc/sdpa.env.in
+++ b/sdpa/etc/sdpa.env.in
@@ -13,23 +13,25 @@ function prepend_path ()
     eval "$var=$val"
 }
 
-prefix=
-default_prefix="@CMAKE_INSTALL_PREFIX@"
-version="@PROJECT_REVISION@"
-
-if [ -n "$SDPA_HOME" ] ; then
-    prefix="$SDPA_HOME"
-else
-    if [ -r "$HOME/.sdpa/home" ] ; then
-	prefix=$(cat "$HOME/.sdpa/home")
-    else
-	prefix="${default_prefix}"
+if [ -z "$SDPA_HOME" ] ; then
+    if [ -z "${BASH_SOURCE[0]}" ] ; then
+        echo >&2 "SDPA_HOME is not set, please set it to the installation"
+        return 1
     fi
+    mypath=$(dirname "${BASH_SOURCE[0]}")
+    case "$mypath" in
+        /*) mypath="$mypath" ;;
+        *)  mypath="$PWD/$mypath" ;;
+    esac
+    SDPA_HOME=$(cd "${mypath}/../.." && pwd)
+    unset mypath
 fi
 
+prefix="$SDPA_HOME"
+
 if [ -z "$prefix" -o ! -d "$prefix" ] ; then
-    echo "cannot access \`$prefix': no such directory" >&2
-    echo "please export SDPA_HOME or write the path to $HOME/.sdpa/home" >&2
+    echo "cannot access '$prefix': no such directory" >&2
+    return 1
 else
     if [ -z "$SDPA_LOADED" -o -n "$FORCE_LOAD_SDPA" ]; then
 	if [ -n "$FORCE_LOAD_SDPA" ]
@@ -40,7 +42,6 @@ else
 	export SDPA_HOME="$prefix"
 	export SDPA_LIBEXEC="$prefix/libexec/sdpa"
 	export SDPA_PLUGINS="$prefix/libexec/fhg/plugins"
-	export SDPA_VERSION="$version"
 
 	prepend_path PATH "${SDPA_HOME}/bin"
 	prepend_path LD_LIBRARY_PATH "${prefix}/lib:${SDPA_LIBEXEC}"
