gspc: new: added more environment queries: bin-path, etc-path, plugin-path, lib-path

diff --git a/sdpa/bin/pbs/gspc b/sdpa/bin/pbs/gspc
--- a/sdpa/bin/pbs/gspc
+++ b/sdpa/bin/pbs/gspc
@@ -1,7 +1,14 @@
 #!/bin/bash
 
 mydir=$(dirname $(which "$0"))
-exec_path=$(readlink -f "${mydir}/../libexec/sdpa/scripts")
+
+prefix_path=$(readlink -f "${mydir}/../")
+exec_path="${prefix_path}/libexec/sdpa/scripts"
+etc_path="${prefix_path}/etc"
+bin_path="${prefix_path}/bin"
+lib_path="${prefix_path}/lib"
+plugin_path="${prefix_path}/libexec/fhg/plugins"
+
 verbose=0
 
 . "${exec_path}/gspc-sh-version"
@@ -49,6 +56,42 @@ while true ; do
                 exit 1
             fi
             echo "$exec_path"
+            shift
+            exit 0
+            ;;
+        --etc-path)
+            if [ -z "${etc_path}" ] ; then
+                echo >&2 "could not deduce etc-path"
+                exit 1
+            fi
+            echo "$etc_path"
+            shift
+            exit 0
+            ;;
+        --bin-path)
+            if [ -z "${bin_path}" ] ; then
+                echo >&2 "could not deduce bin-path"
+                exit 1
+            fi
+            echo "$bin_path"
+            shift
+            exit 0
+            ;;
+        --lib-path)
+            if [ -z "${lib_path}" ] ; then
+                echo >&2 "could not deduce lib-path"
+                exit 1
+            fi
+            echo "$lib_path"
+            shift
+            exit 0
+            ;;
+        --plugin-path)
+            if [ -z "${plugin_path}" ] ; then
+                echo >&2 "could not deduce plugin-path"
+                exit 1
+            fi
+            echo "$plugin_path"
             shift
             exit 0
             ;;
