scripts: inline start_proc into start_kvs: only use

diff --git a/sdpa/bin/pbs/sdpa b/sdpa/bin/pbs/sdpa
--- a/sdpa/bin/pbs/sdpa
+++ b/sdpa/bin/pbs/sdpa
@@ -150,38 +150,6 @@ function is_proc_alive ()
     fi
 }
 
-function start_proc ()
-{
-    local name="$1" ; shift
-    local binary="$1" ; shift
-
-    # check for old one
-    local pid_file="$state_dir/$name.pid"
-    local log_file="$state_dir/log/$name.log"
-    local pid=$( cat "$pid_file" 2>/dev/null )
-    if is_proc_alive "$name" "$pid" ; then
-        echo "- ${name}: old process running with pid ${pid}" >&2
-        return 2
-    fi
-
-    :> "$pid_file"
-    debug $binary "$@"
-    $binary "$@" </dev/null >"$log_file" 2>&1
-    for (( i = 0 ; i < 6 ; ++i )) ; do
-        sleep 0.5
-        pid=$( cat "$pid_file" 2>/dev/null )
-        if [ -n "$pid" ] ; then
-            if is_proc_alive "$name" "$pid" ; then
-                echo "+ $name ($pid)" >&2
-                return 0
-            fi
-        fi
-    done
-    echo "- $name (dead), check '$log_file' for more - here are the last 3 lines:"
-    tail -n 3 "$log_file" >&2
-    return 1
-}
-
 function stop_proc ()
 {
     local name="$1" ; shift
@@ -250,16 +218,39 @@ function status_agent ()
 
 function start_kvs ()
 {
-    if ! start_proc "fhgkvsd" "$SDPA_HOME/bin/fhgkvsd" --bind "0" --port '*' "--pidfile" "$state_dir/fhgkvsd.pid" "--daemonize" > "${state_dir}/kvs.port"; then
+    # check for old one
+    local pid_file="$state_dir/fhgkvsd.pid"
+    local log_file="$state_dir/log/fhgkvsd.log"
+    local pid=$( cat "$pid_file" 2>/dev/null )
+    if is_proc_alive "fhgkvsd" "$pid" ; then
+        echo "- fhgkvsd: old process running with pid ${pid}" >&2
         log "E: could not start kvs, giving up!"
         return 1
     fi
-    local kvs_host=$(hostname -f)
-    local kvs_port=$(cat "${state_dir}/log/fhgkvsd.log")
-    echo -n "${kvs_host}" > "${state_dir}/kvs.host"
-    echo -n "${kvs_port}" > "${state_dir}/kvs.port"
-    log "I: kvs started at ${kvs_host}:${kvs_port}"
-    return 0
+
+    :> "$pid_file"
+    local binary="$SDPA_HOME/bin/fhgkvsd"
+    debug $binary --bind "0" --port '*' "--pidfile" "${pid_file}" "--daemonize"
+    $binary --bind "0" --port '*' "--pidfile" "${pid_file}" "--daemonize" </dev/null >"$log_file" 2>&1
+    for (( i = 0 ; i < 6 ; ++i )) ; do
+        sleep 0.5
+        pid=$( cat "$pid_file" 2>/dev/null )
+        if [ -n "$pid" ] ; then
+            if is_proc_alive "fhgkvsd" "$pid" ; then
+                echo "+ fhgkvsd ($pid)" >&2
+                local kvs_host=$(hostname -f)
+                local kvs_port=$(cat "${state_dir}/log/fhgkvsd.log")
+                echo -n "${kvs_host}" > "${state_dir}/kvs.host"
+                echo -n "${kvs_port}" > "${state_dir}/kvs.port"
+                log "I: kvs started at ${kvs_host}:${kvs_port}"
+                return 0
+            fi
+        fi
+    done
+    echo "- fhgkvsd (dead), check '$log_file' for more - here are the last 3 lines:"
+    tail -n 3 "$log_file" >&2
+    log "E: could not start kvs, giving up!"
+    return 1
 }
 
 function stop_kvs ()
