sdpa: pbs: inline gspc-log

diff --git a/sdpa/bin/pbs/sdpa-selftest b/sdpa/bin/pbs/sdpa-selftest
--- a/sdpa/bin/pbs/sdpa-selftest
+++ b/sdpa/bin/pbs/sdpa-selftest
@@ -6,14 +6,15 @@ fi
 
 . "${SDPA_HOME}/etc/sdpa/sdpa.env"
 
-gspc_bin=$(which gspc)
-if ! test -x "${gspc_bin}" ; then
-    echo >&2 "gspc is not in the PATH"
-    exit 1
-fi
+function log_info ()
+{
+    echo -e >&2 "[I] (selftest): $@"
+}
 
-gspc="gspc -v"
-log="$gspc log --tag selftest"
+function log_error ()
+{
+    echo -e >&2 "[E] (selftest): $@"
+}
 
 function require_executable ()
 {
@@ -21,7 +22,7 @@ function require_executable ()
     local bin=$(which "$name")
 
     if ! test -x "$bin" ; then
-        $log --error "executable '$name' not found"
+        log_error "executable '$name' not found"
         exit 2
     fi
 }
@@ -31,12 +32,12 @@ function require_readable ()
     local name="${1}" ; shift
 
     if ! test -r "$name" ; then
-        $log --error "file '$name' not readable"
+        log_error "file '$name' not readable"
         exit 2
     fi
 }
 
-$log --info "performing self-test"
+log_info "performing self-test"
 
 xml="$SDPA_HOME/libexec/sdpa/apps/selftest/selftest.xml"
 require_readable "$xml"
@@ -56,7 +57,7 @@ function sigterm()
 }
 trap sigterm TERM
 
-$log --info "building job description..."
+log_info "building job description..."
 challenge=$(date +%s | md5sum | awk '{print $1}')
 if [ $? -ne 0 ] ; then
     challenge="dummy"
@@ -65,7 +66,7 @@ fi
 expected_response="sdpa.response.$challenge"
 
 if ! cat "$xml" | pnetc | pnetput -p challenge=\"$challenge\" > "$job_desc" ; then
-    $log --error "could not generate job description and place tokens"
+    log_error "could not generate job description and place tokens"
     exit 5
 fi
 
@@ -80,7 +81,7 @@ cleanup()
 }
 trap cleanup EXIT TERM INT
 
-$log --info "(re-)starting SDPA..."
+log_info "(re-)starting SDPA..."
 
 runtime_started=true
 err=$(sdpa restart 2>&1)
@@ -88,7 +89,7 @@ ec=$?
 if [ $ec -ne 0 ] ; then
     sdpa stop >/dev/null 2>&1
     runtime_started=false
-    $log --error "restart failed: $err"
+    log_error "restart failed: $err"
     exit $ec
 fi
 
@@ -97,53 +98,53 @@ ec=$?
 if [ $ec -ne 0 ] ; then
     sdpa stop >/dev/null 2>&1
     runtime_started=false
-    $log --error "status failed (may indicate license problems): $err"
+    log_error "status failed (may indicate license problems): $err"
     exit $ec
 fi
 
-$log --info "computing response for challenge: $challenge"
+log_info "computing response for challenge: $challenge"
 
-$log --info "submitting job..."
+log_info "submitting job..."
 job_id=$(sdpac submit "$job_desc")
-$log --info "JOB-ID: $job_id"
+log_info "JOB-ID: $job_id"
 
 walltime=120
-$log --info "waiting at most $walltime seconds for job to return..."
+log_info "waiting at most $walltime seconds for job to return..."
 job_state=42
 for ((i=0 ; i < $walltime ; ++i)) ; do
     sleep 1
     job_status=$(sdpac status "$job_id")
     if echo "$job_status" | grep -q -i -e 'finished' ; then
-        $log --info "job has finished"
+        log_info "job has finished"
         job_state=0
         break
     elif echo "$job_status" | grep -q -i -e 'failed' ; then
-        $log --error "job has failed"
+        log_error "job has failed"
         job_state=1
         break
     elif echo "$job_status" | grep -q -i -e 'canceled' ; then
-        $log --error "job has been canceled"
+        log_error "job has been canceled"
         job_state=2
         break
     fi
 done
 
 if [ "$job_state" -ne 0 ] ; then
-    $log --error "self test job could not be executed!"
+    log_error "self test job could not be executed!"
     sdpa stop
     exit 8
 fi
 
-$log --info "I: retrieving results"
+log_info "I: retrieving results"
 if ! sdpac --force -o "$job_desc" results "$job_id" 2>/dev/null ; then
-    $log --error "could not retrieve results"
+    log_error "could not retrieve results"
     rm "$job_desc"
     sdpa stop
     exit 6
 fi
 
 if ! sdpac delete "$job_id" ; then
-    $log --error "could not delete job"
+    log_error "could not delete job"
     rm "$job_desc"
     sdpa stop
     exit 7
@@ -151,9 +152,9 @@ fi
 
 response=$(pnetget < "$job_desc" --type=output response | sed -e 's/^"//g' -e 's/"$//g')
 if [ x"$response" != x"$expected_response" ] ; then
-    $log --error "response: '$response' does not match expected response: '$expected_response'"
+    log_error "response: '$response' does not match expected response: '$expected_response'"
 else
-    $log --info "got correct response"
+    log_info "got correct response"
 fi
 
 if [ -z "$USER" ] ; then
@@ -167,4 +168,4 @@ rm "$job_desc"
 sdpa stop >/dev/null 2>&1
 runtime_started=false
 
-$log --info "Congratulations $greeting, your SDPA installation is working!"
+log_info "Congratulations $greeting, your SDPA installation is working!"
