implemented multiple instances per user
	- a user can start more than one instance of SDPA on a disjunct set of
	  nodes by specifying different 'state' directories.
	- the state directory contains the generated 'sdpa.env' file as well as
	  pidfiles
	- the syntax is:

		$ sdpa -s <state-dir> init <node-file>
		$ sdpa -s <state-dir> start/stop/status

		or

		$ export SDPA_STATE_DIR=<state-dir>
		$ sdpa init/start/stop/status

	- by default the old '~/.sdpa/state' directory will be used.

diff --git a/sdpa/bin/pbs/sdpa b/sdpa/bin/pbs/sdpa
--- a/sdpa/bin/pbs/sdpa
+++ b/sdpa/bin/pbs/sdpa
@@ -216,10 +216,10 @@ function isatty()
     local f="$1" ; shift
     f=$(readlink -f "$f")
     if [ -e "$f" ] ; then
-	tty -s < "$f" >/dev/null 2>&1
-	return $?
+        tty -s < "$f" >/dev/null 2>&1
+        return $?
     else
-	return 1
+        return 1
     fi
 }
 
@@ -230,7 +230,7 @@ function is_unattended ()
     fi
 
     if ! isatty /dev/stdin ; then
-	return 0
+        return 0
     fi
 
     return 1
@@ -727,21 +727,21 @@ to adjust the amount.
     local gpid_dir="$DEFAULT_GPI_PRIV_DIR"
 
     if [ -z "$DEFAULT_GPI_PRIV_DIR" ] ; then
-	for gpi_prog in "gpid.exe" "gpid.bin" ; do
-	    gpid_pid=$(ps -C $gpi_prog -o pid= | tr -d ' ')
-	    if [ -z "$gpid_pid" ] ; then
-		continue
-	    fi
-	    gpid_dir=$(cat /proc/$gpid_pid/cmdline 2>/dev/null | tr '\0' ' ' | grep -o -- '-p [^ ]*' | cut -d' ' -f 2)
-	    if [ -d "$gpid_dir" ] ; then
-		break
-	    fi
-	done
+        for gpi_prog in "gpid.exe" "gpid.bin" ; do
+            gpid_pid=$(ps -C $gpi_prog -o pid= | tr -d ' ')
+            if [ -z "$gpid_pid" ] ; then
+                continue
+            fi
+            gpid_dir=$(cat /proc/$gpid_pid/cmdline 2>/dev/null | tr '\0' ' ' | grep -o -- '-p [^ ]*' | cut -d' ' -f 2)
+            if [ -d "$gpid_dir" ] ; then
+                break
+            fi
+        done
     fi
 
     if [ -z "$gpid_dir" ] ; then
-	log "W: could not discover GPI priviledged directory, using /"
-	gpid_dir="/"
+        log "W: could not discover GPI priviledged directory, using /"
+        gpid_dir="/"
     fi
 
     gpid_dir=$(get "gpi.priv_dir" "$gpid_dir")
@@ -900,8 +900,8 @@ function generate_environment ()
 
     kvs_port=$(get "plugin.kvs.port")
     if [ -z "$kvs_port" ] ; then
-	log "E: could not get kvs port from config!"
-	return 1
+        log "E: could not get kvs port from config!"
+        return 1
     fi
     echo export KVS_URL="$(hostname -s):${kvs_port:?}"
 
@@ -914,9 +914,6 @@ function generate_environment ()
                 ;;
             log.server.url)
                 echo export FHGLOG_to_server="$val"
-                ;;
-            kvs.store)
-                echo export KVS_STORE="$val"
                 ;;
             kvs.url)
                 echo export KVS_URL="$val"
@@ -936,12 +933,6 @@ function generate_environment ()
             sdpa.log_dir)
                 echo export SDPA_LOG_DIR="$val"
                 ;;
-            sdpa.state_dir)
-                echo export SDPA_STATE_DIR="$val"
-                ;;
-            sdpa.node_file)
-                echo export SDPA_NODEFILE="$val"
-                ;;
             sdpa.home)
                 ;;
             *)
@@ -956,6 +947,7 @@ function generate_environment ()
         # sanitize HOME
         export SDPA_HOME="$(echo $SDPA_HOME | sed -e 's,/\+$,,')"
     fi
+
     export SDPA_LIBEXEC="$SDPA_HOME/libexec/sdpa"
     export SDPA_PLUGINS="$SDPA_HOME/libexec/fhg/plugins"
 
@@ -976,19 +968,19 @@ function generate_environment ()
     OLDIFS="$IFS"
     IFS=":"
     for d in $SDPA_APP_PATH ; do
-	# eval echo: resolve "~"
-	app_directories=( ${app_directories[@]} $(eval echo "$d") )
+        # eval echo: resolve "~"
+        app_directories=( ${app_directories[@]} $(eval echo "$d") )
     done
     IFS="$OLDIFS"
 
     app_directories=( ${app_directories[@]} "$HOME/.sdpa/modules" )
 
     for app_dir in ${app_directories[@]} ; do
-	for f in $(find "$app_dir" -type f -name "*.so" ) ; do
+        for f in $(find "$app_dir" -type f -name "*.so" ) ; do
             mod_dir=$(dirname "$f")
             prepend_to_path PC_LIBRARY_PATH "$mod_dir"
             prepend_to_path LD_LIBRARY_PATH "$mod_dir"
-	done
+        done
     done
 
     echo export LD_LIBRARY_PATH="$LD_LIBRARY_PATH"
@@ -1003,15 +995,38 @@ function dump_config ()
 
 function initialize ()
 {
-    local hostfile="$1"; shift
-    local node_file=$(get "sdpa.node_file" "$SDPA_NODEFILE")
+    local hostfile=
+    local node_file=
+
+    argv="$@"
+    OPTIND=1
+    while getopts ":hF:n:s:" opt $argv ; do
+        case $opt in
+            h)
+                echo >&2 "usage: init: [-h] [-F hostfile] [-s state-dir]"
+                return 0
+                ;;
+            F)
+                hostfile="$OPTARG"
+                shift 2
+                ;;
+            s)
+                state_dir="$OPTARG"
+                shift 2
+                ;;
+            \?)
+                shift
+                ;;
+        esac
+    done
 
     if [ -z "$hostfile" ] ; then
-        hostfile="$PBS_NODEFILE"
+        hostfile="$1"; shift
     fi
 
     if [ -z "$hostfile" ] ; then
-        log "E: usage: init [hostfile] or export PBS_NODEFILE"
+        log "E: hostfile not set"
+        log "usage: init: [-h] [-F hostfile] [-s state-dir]"
         return 1
     fi
 
@@ -1026,6 +1041,13 @@ function initialize ()
             return 1
         fi
     fi
+
+    if [ ! -d "${state_dir}" ] ; then
+        log "I: creating state directory: ${state_dir}"
+        mkdir -p "${state_dir}"
+    fi
+
+    node_file="${state_dir}/nodefile"
 
     if ! cp "$hostfile" "$node_file" ; then
         log "E: could not copy nodefile from '$hostfile' to '$node_file'"
@@ -1167,12 +1189,12 @@ function start_proc ()
         $binary $@ </dev/null >"$log_file" 2>&1
         for (( i = 0 ; i < 6 ; ++i )) ; do
             sleep 0.5
-	    pid=$( cat "$pid_file" 2>/dev/null )
-	    if [ -n "$pid" ] ; then
-		if is_proc_alive "$name" "$pid" ; then
+            pid=$( cat "$pid_file" 2>/dev/null )
+            if [ -n "$pid" ] ; then
+                if is_proc_alive "$name" "$pid" ; then
                     echo "+ $name ($pid)" >&2
                     return 0
-		fi
+                fi
             fi
         done
         echo "- $name (dead)" >&2
@@ -1233,7 +1255,7 @@ function start_agent ()
         node=localhost
     fi
 
-    err=$(rexec "$node" "$SDPA_SCRIPT_DIR/start-agent" -P "$state_dir/agent.$name.pid" -D -n "$name" -m "$master" $@ </dev/null 2>&1)
+    err=$(rexec "$node" "$SDPA_SCRIPT_DIR/start-agent" -s "$state_dir" -P "$state_dir/agent.$name.pid" -D -n "$name" -m "$master" $@ </dev/null 2>&1)
     ec=$?
     if [ $ec -eq 0 ] ; then
         echo "$name" >&2
@@ -1291,11 +1313,11 @@ function start_kvs ()
     fi
     kvs_port=$(get "plugin.kvs.port")
     if [ -z "$kvs_port" ] ; then
-	log "E: could not get kvs port from config!"
-	return 1
+        log "E: could not get kvs port from config!"
+        return 1
     fi
 
-    if ! start_proc "fhgkvsd" "$SDPA_HOME/bin/fhgkvsd" "-C" "-b" "0" "-p" "${kvs_port}" "--pidfile" "$state_dir/fhgkvsd.pid" "--daemonize"; then
+    if ! start_proc "fhgkvsd" "$SDPA_HOME/bin/fhgkvsd" -s "$state_dir/kvs.dat" "-C" "-b" "0" "-p" "${kvs_port}" "--pidfile" "$state_dir/fhgkvsd.pid" "--daemonize"; then
         log "E: could not start kvs, giving up!"
         return 1
     else
@@ -1319,7 +1341,7 @@ function start_orch ()
         log "E: Orchestrator must be started on the master node"
         exit 1
     fi
-    if ! start_proc "orchestrator" "start-orch" "-P" "$state_dir/orchestrator.pid" "-D" ; then
+    if ! start_proc "orchestrator" "start-orch" "-s" "$state_dir" "-P" "$state_dir/orchestrator.pid" "-D" ; then
         echo "E: could not start orchestrator, giving up!" >&2
         return 1
     else
@@ -1356,14 +1378,14 @@ function stop_agg ()
 
 function node_loop ()
 {
-    if [ ! -r "$SDPA_NODEFILE" ] ; then
-        echo "Cannot read nodefile: $SDPA_NODEFILE" >&2
+    if [ ! -r "${state_dir}/nodefile" ] ; then
+        echo "Cannot read nodefile: ${state_dir}/nodefile" >&2
         return 1
     fi
 
     local body="$1" ; shift
 
-    nodes=$(uniq "$SDPA_NODEFILE")
+    nodes=$(uniq "${state_dir}/nodefile")
 
     local rc=0
     local bunch_size=16
@@ -1664,7 +1686,7 @@ function start_drts_on_node ()
         master="nre-$node"
     fi
 
-    err=$(rexec "$node" "$SDPA_SCRIPT_DIR/start-drts" -D -m "$master" -c "$per_node" $@ 2>&1)
+    err=$(rexec "$node" "$SDPA_SCRIPT_DIR/start-drts" -s "$state_dir" -D -m "$master" -c "$per_node" $@ 2>&1)
     ec=$?
     if [ $ec -eq 0 ] ; then
         return 0
@@ -1722,7 +1744,7 @@ function start_gui ()
     fi
     local gui_host=$(echo "$gui_url" | cut -d ':' -f 1)
 
-    local cmd="$SDPA_SCRIPT_DIR/start-gui $gui_port $log_port"
+    local cmd="$SDPA_SCRIPT_DIR/start-gui -s $state_dir -G $gui_port -L $log_port"
     if [ "$gui_host" != "$(hostname -f)" ] ; then
         log "W: gui-url ($gui_url) specifies a different host than your current host: $(hostname -f)"
         cmd="ssh -X $gui_host $cmd"
@@ -1745,7 +1767,7 @@ function start_gpi ()
     fi
     local gpi_enabled=$(get "gpi.enabled" "true")
     if [ x"$gpi_enabled" == x"true" ] ; then
-        if ! start_proc "gpi-space" "$SDPA_SCRIPT_DIR/start-gpi" "-f" "-P" "$HOME/.sdpa/state/gpi-space.pid" "-m" $(get "gpi.memory_size" "${DEFAULT_GPI_MEMSIZE:?}"); then
+        if ! start_proc "gpi-space" "$SDPA_SCRIPT_DIR/start-gpi" "-s" "$state_dir" "-f" "-P" "$state_dir/gpi-space.pid" "-m" $(get "gpi.memory_size" "${DEFAULT_GPI_MEMSIZE:?}"); then
             log "E: could not start GPI, giving up!"
             return 1
         else
@@ -1832,7 +1854,7 @@ function program_status ()
 
 function status_orch ()
 {
-    is_proc_alive "orchestrator" $(cat "$state_dir/orchestrator.pid")
+    is_proc_alive "orchestrator" $(cat "$state_dir/orchestrator.pid" 2>/dev/null)
 }
 
 function status_agg ()
@@ -1842,7 +1864,7 @@ function status_agg ()
 
 function status_kvs ()
 {
-    is_proc_alive "fhgkvsd" $(cat "$state_dir/fhgkvsd.pid")
+    is_proc_alive "fhgkvsd" $(cat "$state_dir/fhgkvsd.pid" 2>/dev/null)
 }
 
 function status_gpi ()
@@ -1992,8 +2014,6 @@ function submit ()
 function configure()
 {
     test -e "$state_dir/sdpa.env" && source "$state_dir/sdpa.env"
-    # write the kvs url to a file
-    echo "$KVS_URL" > "$state_dir/kvs.url"
 }
 
 function on_valid_host ()
@@ -2010,11 +2030,11 @@ function on_valid_host ()
             return 0
         else
             log "W: your hostname ($host) does not match any in $state_dir/nodefile"
-	    return 1
+            return 1
         fi
     else
         log "E: no nodefile present"
-	return 2
+        return 2
     fi
     return 1
 }
@@ -2185,6 +2205,12 @@ if [ "$1" = "setup" ] ; then
     exit $?
 fi
 
+if [ "$1" = "-s" ] ; then
+    shift
+    state_dir="$1"; shift
+    export SDPA_STATE_DIR="$state_dir"
+fi
+
 if setup_required ; then
     if setup ; then
         log "I: setup complete"
@@ -2201,7 +2227,6 @@ if [ "$1" = "init" ] ; then
         log "E: could not initialize!"
         exit 1
     else
-        log "I: please don't forget to execute \"eval \$(sdpa load)\""
         exit 0
     fi
 fi
diff --git a/sdpa/bin/pbs/start-gui b/sdpa/bin/pbs/start-gui
--- a/sdpa/bin/pbs/start-gui
+++ b/sdpa/bin/pbs/start-gui
@@ -1,20 +1,49 @@
 #!/bin/bash
-### avoid strange behaviour with temporary inconsistency
-### on Panasas Filesystems:
-###
-###     the test -r was sucessful but the source didn't
-###     source anything
-###
-###
-cat ~/.sdpa/state/sdpa.env >/dev/null 2>&1
 
-test -r ~/.sdpa/state/sdpa.env && source ~/.sdpa/state/sdpa.env
+function usage ()
+{
+    cat >&2 <<EOF
+usage: $0 [options]
 
-echo "Running $(which sdpa-gui) $@ on $(hostname)" >&2
+    -h: print this help
+    -s dir: state-dir
+EOF
+}
 
-err=$(sdpa-gui $@ 2>&1)
+state_dir="~/.sdpa/state"
+log_port=
+gui_port=
+
+while getopts ":hG:L:s:" opt; do
+    case $opt in
+	h)
+	    usage
+	    exit 0
+	    ;;
+	G)
+	    gui_port=$OPTARG
+	    ;;
+	L)
+	    log_port=$OPTARG
+	    ;;
+	s)
+	    state_dir="$OPTARG"
+	    ;;
+	\?)
+	    echo "invalid option: -$OPTARG" >&2
+	    echo "try: $0 -h" >&2
+	    exit 1
+	    ;;
+    esac
+done
+
+test -r "${state_dir}/sdpa.env" && source "${state_dir}/sdpa.env"
+
+echo >&2 "Running $(which sdpa-gui) $gui_port $log_port on $(hostname)"
+
+err=$(sdpa-gui $gui_port $log_port 2>&1)
 ec=$?
 if [ $ec -ne 0 ] ; then
-	echo "sdpa-gui failed: $ec: $err" >&2
+	echo >&2 "sdpa-gui failed: $ec: $err"
 	exit $ec
 fi
diff --git a/sdpa/bin/pbs/start-orch b/sdpa/bin/pbs/start-orch
--- a/sdpa/bin/pbs/start-orch
+++ b/sdpa/bin/pbs/start-orch
@@ -6,69 +6,81 @@
 ###     source anything
 ###
 ###
-cat ~/.sdpa/state/sdpa.env >/dev/null 2>&1
-
-test -r ~/.sdpa/state/sdpa.env && source ~/.sdpa/state/sdpa.env
-
 debug=false
 bind_addr='0'
 name="orchestrator"
-bkp_dir="${SDPA_SCRATCH_DIR}/state"
-kvs_url="$KVS_URL"
-bin=$(which orchestrator 2>/dev/null)
+kvs_url=
 daemonize=false
 pidfile=
-if [ -z "$bin" ] ; then
-    log "# could not find orchestrator binary in the path!"
-    exit 1
+state_dir="~/.sdpa/state"
+
+while getopts ":hgn:l:d:k:DP:s:" opt; do
+    case $opt in
+        g)
+            debug=true
+            ;;
+        l)
+            bind_addr=$OPTARG
+            ;;
+        n)
+            name=$OPTARG
+            ;;
+        k)
+            kvs_url=$OPTARG
+            ;;
+        D)
+            daemonize=true
+            ;;
+        P)
+            pidfile=$OPTARG
+            ;;
+        s)
+            state_dir=$OPTARG
+            ;;
+        h)
+            echo "usage: $0 [-h] [-g] [-l interface] [-n name] [-b backup-dir]" >&2
+            echo "    -h : print this help" >&2
+            echo "    -l : address to listen on (default: $bind_addr)" >&2
+            echo "    -n : name (default: $name)" >&2
+            echo "    -k : kvs url" >&2
+            echo "    -g : run within gdb" >&2
+            echo "    -D : daemonize" >&2
+            echo "    -P pidfile: write pid to this file and lock it" >&2
+            echo "    -s dir: sdpa state dir to use" >&2
+            exit 0
+            ;;
+        \?)
+            echo "Invalid option: -$OPTARG" >&2
+            exit 1
+    esac
+done
+
+if [ -r "$state_dir/sdpa.env" ] ; then
+    source "$state_dir/sdpa.env"
+else
+    echo >&2 "must be executed within sdpa!"
 fi
 
-while getopts ":hgn:l:d:k:DP:" opt; do
-  case $opt in
-	g)
-	  debug=true
-	;;
-	l)
-	  bind_addr=$OPTARG
-	;;
-        n)
-          name=$OPTARG
-        ;;
-	b)
-	  bkp_dir=$OPTARG
-	;;
-        k)
-	  kvs_url=$OPTARG
-	  ;;
-        D)
-	  daemonize=true
-	  ;;
-        P)
-	  pidfile=$OPTARG
-	  ;;
-	h)
-	  echo "usage: $0 [-h] [-g] [-l interface] [-n name] [-b backup-dir]" >&2
-	  echo "    -h : print this help" >&2
-	  echo "    -l : address to listen on (default: $bind_addr)" >&2
-	  echo "    -n : name (default: $name)" >&2
-          echo "    -b : path to the backup directory (${bkp_dir})" >&2
-	  echo "    -k : kvs url" >&2
-	  echo "    -g : run within gdb" >&2
-	  echo "    -D : daemonize" >&2
-	  echo "    -P pidfile: write pid to this file and lock it" >&2
-	  exit 0
-	;;
-	\?)
-	  echo "Invalid option: -$OPTARG" >&2
-	  exit 1
-  esac
-done
+if [ -z "$kvs_url" ]
+then
+    kvs_url="$KVS_URL"
+fi
+
+# check environment
+
+if [ -z "$kvs_url" ]
+then
+    echo >&2 "E: kvs url was not specified!"
+    exit 2
+fi
 
 log "Running $name at $bind_addr"
 
-argv="-u $bind_addr -n ${name} -k ${kvs_url}"
+argv="$SDPA_HOME/bin/orchestrator -u $bind_addr -n ${name} -k ${kvs_url}"
 stateful="$(fhgcfg -f ~/.sdpa/configs/sdpa.rc -g sdpa.stateful -v false)"
 if [ x"$stateful" = x"true" ] ; then
+    bkp_dir="${state_dir}/orch"
+    mkdir -p "${bkp_dir}"
     argv="$argv -d ${bkp_dir}"
 fi
 if $daemonize && ! $debug ; then
@@ -80,7 +92,7 @@ fi
 
 if $debug ; then
     log "running within gdb..."
-    FHGLOG_to_console="stderr" gdb -ex run --args $bin $argv
+    FHGLOG_to_console="stderr" gdb -ex run --args $argv
 else
-    FHGLOG_to_file="$SDPA_LOG_DIR/orch.`hostname -s`.log" exec $bin $argv
+    FHGLOG_to_file="$SDPA_LOG_DIR/orch.`hostname -s`.log" exec $argv
 fi
diff --git a/sdpa/bin/pbs/status-drts b/sdpa/bin/pbs/status-drts
--- a/sdpa/bin/pbs/status-drts
+++ b/sdpa/bin/pbs/status-drts
@@ -1,16 +1,4 @@
 #!/bin/bash
-
-### avoid strange behaviour with temporary inconsistency
-### on Panasas Filesystems:
-###
-###     the test -r was sucessful but the source didn't
-###     source anything
-###
-###
-cat ~/.sdpa/state/sdpa.env >/dev/null 2>&1
-
-test -r ~/.sdpa/state/sdpa.env && source ~/.sdpa/state/sdpa.env
-
 name=
 long=false
 short=false
@@ -35,25 +23,25 @@ EOF
 
 while getopts ":hi:n:ls" opt; do
     case $opt in
-	h)
-	    usage
-	    exit 0
-	    ;;
-	i)
-	    identity=$OPTARG
-	    ;;
-	n)
-	    name=$OPTARG
-	    ;;
-	l)
-	    long=true
-	    ;;
-	s)
-	    short=true
-	    ;;
-	\?)
-	    echo "Invalid option: -$OPTARG" >&2
-	    exit 1
+        h)
+            usage
+            exit 0
+            ;;
+        i)
+            identity=$OPTARG
+            ;;
+        n)
+            name=$OPTARG
+            ;;
+        l)
+            long=true
+            ;;
+        s)
+            short=true
+            ;;
+        \?)
+            echo "Invalid option: -$OPTARG" >&2
+            exit 1
     esac
 done
 
@@ -62,42 +50,42 @@ function status ()
     local name="$1" ; shift
     local pids=
     if [ -z "$name" ] ; then
-	pids=$(ps aux | grep -v [s]tatus-drts | grep "[f]hgkernel.*-s plugin.drts.name=" | awk '{print $2;}')
+        pids=$(ps aux | grep -v [s]tatus-drts | grep "[f]hgkernel.*-s plugin.drts.name=" | awk '{print $2;}')
     else
-	pids=$(ps aux | grep -v [s]tatus-drts | grep "[f]hgkernel.*-s plugin.drts.name=\<$name\>" | awk '{print $2;}')
+        pids=$(ps aux | grep -v [s]tatus-drts | grep "[f]hgkernel.*-s plugin.drts.name=\<$name\>" | awk '{print $2;}')
     fi
     if [ -z "$pids" ] ; then
-	return 1
+        return 1
     else
-	echo $pids
-	return 0
+        echo $pids
+        return 0
     fi
 }
 
 if [ -z "$name" ] ; then
     if [ -n "$identity" ] ; then
-	name="${name_prefix}-${identity}"
+        name="${name_prefix}-${identity}"
     fi
 fi
 
 pids=$(status $name)
 if [ -n "$pids" ] ; then
     if [ -n "$name" ] ; then
-	echo "ok"
-	exit 0
+        echo "ok"
+        exit 0
     else
-	for p in $pids ; do
-	    if $short ; then
-		echo $p
-	    else
-		cmd="$(ps -p $p -o cmd=)"
-		if [ $long == false ] ; then
-		    cmd=$(echo $cmd | sed -e 's/.*-s plugin.drts.name=\([^ ]\+\).*/\1/')
-		fi
-		echo "pid $p := $cmd"
-	    fi
-	done
-	exit 0
+        for p in $pids ; do
+            if $short ; then
+                echo $p
+            else
+                cmd="$(ps -p $p -o cmd=)"
+                if [ $long == false ] ; then
+                    cmd=$(echo $cmd | sed -e 's/.*-s plugin.drts.name=\([^ ]\+\).*/\1/')
+                fi
+                echo "pid $p := $cmd"
+            fi
+        done
+        exit 0
     fi
 else
     exit 1
diff --git a/sdpa/bin/pbs/stop-drts b/sdpa/bin/pbs/stop-drts
--- a/sdpa/bin/pbs/stop-drts
+++ b/sdpa/bin/pbs/stop-drts
@@ -1,14 +1,4 @@
 #!/bin/bash
-### avoid strange behaviour with temporary inconsistency
-### on Panasas Filesystems:
-###
-###     the test -r was sucessful but the source didn't
-###     source anything
-###
-###
-cat ~/.sdpa/state/sdpa.env >/dev/null 2>&1
-
-test -r ~/.sdpa/state/sdpa.env && source ~/.sdpa/state/sdpa.env
 
 function usage ()
 {
@@ -26,21 +16,21 @@ dry_run=false
 
 while getopts ":hi:n" opt; do
     case $opt in
-	h)
-	    usage
-	    exit 0
-	    ;;
-	i)
-	    identity=$OPTARG
-	    ;;
-	n)
-	    dry_run=true
-	    ;;
-	\?)
-	    echo "invalid option: -$OPTARG" >&2
-	    echo "try: $0 -h" >&2
-	    exit 1
-	    ;;
+        h)
+            usage
+            exit 0
+            ;;
+        i)
+            identity=$OPTARG
+            ;;
+        n)
+            dry_run=true
+            ;;
+        \?)
+            echo "invalid option: -$OPTARG" >&2
+            echo "try: $0 -h" >&2
+            exit 1
+            ;;
     esac
 done
 
@@ -51,19 +41,19 @@ function kill_drts ()
     local alive=true
     echo -n "Terminating $pid..."
     for (( i=0; i < 3; ++i )); do
-	echo -n "."
+        echo -n "."
         kill -TERM "$pid" >/dev/null 2>&1
-	if [ $? -ne 0 ] ; then
-	    alive=false
-	fi
-	if [ "$alive" == "false" ] ; then
-	    echo "ok."
-	    return 0
-	fi
-	sleep 0.5
+        if [ $? -ne 0 ] ; then
+            alive=false
+        fi
+        if [ "$alive" == "false" ] ; then
+            echo "ok."
+            return 0
+        fi
+        sleep 0.5
     done
     if [ "$alive" == "true" ] ; then
-	echo "killed."
+        echo "killed."
         kill -KILL "$pid" >/dev/null 2>&1
     fi
 }
@@ -72,22 +62,22 @@ still_running=$(ps -C fhgkernel -o pid=)
 for p in $still_running ; do
     name=$(cat /proc/$p/cmdline | tr '\0' ' ' |  grep -o 'plugin.drts.name=[^ ]\+' | cut -d= -f2)
     if [ -z "$name" ] ; then
-	continue
+        continue
     fi
     if [ -n "$identity" ] ; then
-	if [ x"$name" == x"drts-$(hostname -s)-$identity" ] ; then
-	    if $dry_run ; then
-		echo kill_drts "$p" "$name"
-	    else
-		kill_drts "$p" "$name" >/dev/null 2>&1
-	    fi
-	fi
+        if [ x"$name" == x"drts-$(hostname -s)-$identity" ] ; then
+            if $dry_run ; then
+                echo kill_drts "$p" "$name"
+            else
+                kill_drts "$p" "$name" >/dev/null 2>&1
+            fi
+        fi
     else
-	if $dry_run ; then
-	    echo kill_drts "$p" "$name"
-	else
-	    kill_drts "$p" "$name" >/dev/null 2>&1
-	fi
+        if $dry_run ; then
+            echo kill_drts "$p" "$name"
+        else
+            kill_drts "$p" "$name" >/dev/null 2>&1
+        fi
     fi
 done
 wait
