scripts: selftest: remove reimplementation of `sdpa submit`

diff --git a/sdpa/bin/pbs/sdpa-selftest b/sdpa/bin/pbs/sdpa-selftest
--- a/sdpa/bin/pbs/sdpa-selftest
+++ b/sdpa/bin/pbs/sdpa-selftest
@@ -87,7 +87,6 @@ trap cleanup EXIT
 require_readable "${SDPA_HOME}/share/sdpa/make/common.mk"
 require_readable "${SDPA_HOME}/libexec/sdpa/apps/selftest/selftest.xml"
 require_executable pnetc
-require_executable sdpac
 require_executable pnetput
 require_executable pnetget
 
@@ -127,53 +126,14 @@ if [ $ec -ne 0 ] ; then
     exit $ec
 fi
 
-# todo: remove magic: specify filenames instead of relying on files?
-orchestrator_host=$(cat "${state_dir}/orchestrator.host")
-orchestrator_port=$(cat "${state_dir}/orchestrator.port")
-SDPACFLAGS=(--orchestrator-host "${orchestrator_host}" \
-            --orchestrator-port ${orchestrator_port})
-
 expected_response="sdpa.response.$challenge"
 
 log_info "++ submitting job..."
-job_id=$(sdpac ${SDPACFLAGS[@]} submit "${builddir}/selftest.pnet.put")
-log_info "+++ job-id: $job_id"
-
-walltime=15
-log_info "++++ waiting at most $walltime seconds for job to return..."
-job_state=42
-for ((i=0 ; i < $walltime ; ++i)) ; do
-    job_status=$(sdpac ${SDPACFLAGS[@]} status "$job_id")
-    if echo "$job_status" | grep -q -i -e 'finished' ; then
-        log_info "+++ job has finished"
-        job_state=0
-        break
-    elif echo "$job_status" | grep -q -i -e 'failed' ; then
-        log_error "+++ job has failed"
-        job_state=1
-        break
-    elif echo "$job_status" | grep -q -i -e 'canceled' ; then
-        log_error "+++ job has been canceled"
-        job_state=2
-        break
-    fi
-    sleep 1
-done
-
-if [ "$job_state" -ne 0 ] ; then
-    log_error "++ selftest could not be executed!"
-    exit 8
-fi
-
-log_info "+++ retrieving results"
-if ! sdpac ${SDPACFLAGS[@]} --force -o "${builddir}/result.pnet" results "$job_id" 2>/dev/null ; then
-    log_error "++++ could not retrieve results"
-    exit 6
-fi
-
-if ! sdpac ${SDPACFLAGS[@]} delete "$job_id" ; then
-    log_error "++++ could not delete job"
-    exit 7
+sdpa -s "${state_dir}" submit \
+  "${builddir}/selftest.pnet.put" "${builddir}/result.pnet"
+if [ $? -ne 0 ] ; then
+  log_error "++ selftest could not be submitted/executed"
+  exit 8
 fi
 
 response=$(pnetget < "${builddir}/result.pnet" --type=output response | sed -e 's/^"//g' -e 's/"$//g')
