Revert "pbs: replaced rexec in sdpa script with "gspc rexec""
This reverts commit ae331e8a48237eff661ef80a29766613de4c4a3e.

diff --git a/sdpa/bin/pbs/sdpa b/sdpa/bin/pbs/sdpa
--- a/sdpa/bin/pbs/sdpa
+++ b/sdpa/bin/pbs/sdpa
@@ -187,7 +187,23 @@ function put ()
 
 function rexec ()
 {
-    gspc rexec "${@}"
+    local node="$1"; shift
+    local err
+    local rc
+    local ssh_opts="-q -x -T -n -C -4 -c arcfour,blowfish-cbc -o CheckHostIP=no -o StrictHostKeyChecking=no"
+    local cmd="ssh $ssh_opts $node $@"
+    debug $cmd
+    err=$($cmd 2>&1)
+    rc=$?
+    if [ $rc -eq 0 ] ; then
+        return 0
+    elif [ $rc -eq 255 ] ; then
+        echo "ssh could not connect to $node: $err: $rc" >&2
+        return $rc
+    else
+        echo "$err"
+        return $rc
+    fi
 }
 
 function guess_head_node ()
