start scripts: fixed bug with ~ in quotes not being evaluated

diff --git a/sdpa/bin/pbs/start-gui b/sdpa/bin/pbs/start-gui
--- a/sdpa/bin/pbs/start-gui
+++ b/sdpa/bin/pbs/start-gui
@@ -10,40 +10,45 @@ usage: $0 [options]
 EOF
 }
 
-state_dir="~/.sdpa/state"
+state_dir="$HOME/.sdpa/state"
 log_port=
 gui_port=
 
 while getopts ":hG:L:s:" opt; do
     case $opt in
-	h)
-	    usage
-	    exit 0
-	    ;;
-	G)
-	    gui_port=$OPTARG
-	    ;;
-	L)
-	    log_port=$OPTARG
-	    ;;
-	s)
-	    state_dir="$OPTARG"
-	    ;;
-	\?)
-	    echo "invalid option: -$OPTARG" >&2
-	    echo "try: $0 -h" >&2
-	    exit 1
-	    ;;
+        h)
+            usage
+            exit 0
+            ;;
+        G)
+            gui_port=$OPTARG
+            ;;
+        L)
+            log_port=$OPTARG
+            ;;
+        s)
+            state_dir="$OPTARG"
+            ;;
+        \?)
+            echo "invalid option: -$OPTARG" >&2
+            echo "try: $0 -h" >&2
+            exit 1
+            ;;
     esac
 done
 
-test -r "${state_dir}/sdpa.env" && source "${state_dir}/sdpa.env"
+if [ -r "${state_dir}/sdpa.env" ] ; then
+    source "${state_dir}/sdpa.env"
+else
+    echo >&2 "needs to be executed under SDPA"
+    exit 4
+fi
 
 echo >&2 "Running $(which sdpa-gui) $gui_port $log_port on $(hostname)"
 
 err=$(sdpa-gui $gui_port $log_port 2>&1)
 ec=$?
 if [ $ec -ne 0 ] ; then
-	echo >&2 "sdpa-gui failed: $ec: $err"
-	exit $ec
+        echo >&2 "sdpa-gui failed: $ec: $err"
+        exit $ec
 fi
