pbs: chg: start-* scripts bail out, when kvs url was not set
removes dependency to KVS_URL environment variable set in <state>/sdpa.env

diff --git a/sdpa/bin/pbs/start-agent b/sdpa/bin/pbs/start-agent
--- a/sdpa/bin/pbs/start-agent
+++ b/sdpa/bin/pbs/start-agent
@@ -111,7 +111,8 @@ logprefix="${logdir}/${name}"
 
 if [ -z "$kvs_url" ]
 then
-    kvs_url="$KVS_URL"
+    echo >&2 "kvs url is required, please specify -k"
+    exit 4
 fi
 
 if [ -z "$name" -o -z "$master" ] ; then
diff --git a/sdpa/bin/pbs/start-drts b/sdpa/bin/pbs/start-drts
--- a/sdpa/bin/pbs/start-drts
+++ b/sdpa/bin/pbs/start-drts
@@ -169,13 +169,8 @@ fi
 
 if [ -z "$kvs_url" ]
 then
-    kvs_url="${KVS_URL}"
-fi
-
-
-if [ -z "$kvs_url" ] ; then
-    log "E: no kvs-url specified!"
-    exit 1
+    echo >&2 "kvs url is required, please specify -k"
+    exit 4
 fi
 
 if [ -z "$master" ] ; then
diff --git a/sdpa/bin/pbs/start-orch b/sdpa/bin/pbs/start-orch
--- a/sdpa/bin/pbs/start-orch
+++ b/sdpa/bin/pbs/start-orch
@@ -80,15 +80,8 @@ logprefix="${logdir}/${name}"
 
 if [ -z "$kvs_url" ]
 then
-    kvs_url="$KVS_URL"
-fi
-
-# check environment
-
-if [ -z "$kvs_url" ]
-then
-    echo >&2 "E: kvs url was not specified!"
-    exit 2
+    echo >&2 "kvs url is required, please specify -k"
+    exit 4
 fi
 
 log "Running $name on $(hostname)"
