kvs: drop defaults for host and port everywhere
* remove -k from sdpa boot. let kvs automatically choose port by
  specifying --port '*'. todo: maybe add -k to boot again, if really
  needed. was removed to avoid having a default (which would be '*'
  instead of the previous 2439, but still a default)
* use --kvs-host and --kvs-port in binaries instead of
  $env{KVS_URL},-k/-K/--kvs-url (and splitting that)
* use -k for host and -K for port in scripts (no long-opts…)
* make those parameters required in scripts and binaries
* make plugin.drts.kvs_{host|port} required
* store host and port in $state_dir/kvs.{host|port}. use that in sdpa,
  start-sdpa, drts/drts.cpp, sdpacc and sdpa-selftest.
* removes a 'sleep 1' from start_kvs (not needed as we fork after
  opening socket)
* note: pnete still has hardcoded host and port, just as hard-coded
  orchestrator name. that's only a hack anyway.

diff --git a/sdpa/bin/pbs/start-sdpa b/sdpa/bin/pbs/start-sdpa
--- a/sdpa/bin/pbs/start-sdpa
+++ b/sdpa/bin/pbs/start-sdpa
@@ -1,7 +1,5 @@
 #!/bin/bash
 
-kvs_port=2439
-
 DEFAULT_LOG_PORT="$(( (65535 - 30000 + $(id -u) * 2) % 65535 + 1024 + 0))"
 DEFAULT_GUI_PORT="$(( (65535 - 30000 + $(id -u) * 2) % 65535 + 1024 + 1))"
 log_url="$(hostname -s):${DEFAULT_LOG_PORT}"
@@ -39,7 +37,6 @@ usage: $(basename $0) [options]
         case you don't have permissions for that folder.
   -y: Socket file to communicate with the virtual memory manager
 
-  -k: kvs port (=$kvs_port)
   -l: log url (=${log_url})
   -g: gui url (=${gui_url})
 
@@ -209,7 +206,7 @@ function wait_for_process ()
 
     until [ $retries -eq 0 ]
     do
-        host_port=( $("${sdpa_home}/bin/fhgkvsc" -H "${kvs_host}" -P "${kvs_port}" -g p2p.peer | grep -B 2 "$name" | head -n 2 | awk '{print $3}') )
+        host_port=( $("${sdpa_home}/bin/fhgkvsc" --host "${kvs_host}" --port "${kvs_port}" -g p2p.peer | grep -B 2 "$name" | head -n 2 | awk '{print $3}') )
         if [ ${#host_port[@]} -eq 2 ]
         then
             if wait_for_port_on_host ${retries} "${host_port[0]}" "${host_port[1]}"
@@ -256,7 +253,7 @@ if [ ${#@} -eq 0 ] ; then
 fi
 
 shiftcount=0
-while getopts ":hvnf:S:m:s:C:p:MA:dG:k:x:l:g:H:y:" opt; do
+while getopts ":hvnf:S:m:s:C:p:MA:dG:x:l:g:H:y:" opt; do
     case $opt in
         h)
             usage
@@ -311,11 +308,6 @@ while getopts ":hvnf:S:m:s:C:p:MA:dG:k:x:l:g:H:y:" opt; do
             ;;
         G)
             number_of_groups=$OPTARG
-            shiftcount=$((shiftcount + 2))
-            ;;
-        k)
-            kvs_port=$OPTARG
-            assert_not_empty kvs_port
             shiftcount=$((shiftcount + 2))
             ;;
         x)
@@ -466,7 +458,7 @@ else
     opt_verbose_flag=""
 fi
 
-rexec $master ${sdpa} -s "${state_dir}" start kvs ${kvs_port}
+rexec "${master}" ${sdpa} -s "${state_dir}" start kvs
 ec=$?
 if [ $ec -ne 0 ]
 then
@@ -474,10 +466,13 @@ then
     error 3 "could not start kvs"
 fi
 
-if ! wait_for_port_on_host ${network_retries} "${master}" "${kvs_port}"
+kvs_host=$(cat "${state_dir}/kvs.host")
+kvs_port=$(cat "${state_dir}/kvs.port")
+
+if ! wait_for_port_on_host ${network_retries} "${kvs_host}" "${kvs_port}"
 then
     "${sdpa}" -s "${state_dir}" stop
-    error 3 "could not start kvs: failed to appear at ${master}:${kvs_port} after ${network_retries} seconds"
+    error 3 "could not start kvs: failed to appear at ${kvs_host}:${kvs_port} after ${network_retries} seconds"
 fi
 
 rexec $master "${script_start_orchestrator}" \
@@ -485,7 +480,8 @@ rexec $master "${script_start_orchestrator}" \
     -s "$state_dir" \
     -P "$state_dir/orchestrator.pid" \
     -D \
-    -k "${master}:${kvs_port}" \
+    -k "${kvs_host}" \
+    -K "${kvs_port}" \
     -l "${log_host}:${log_port}" \
     -H "${sdpa_home}" \
     -n "orchestrator"
@@ -496,7 +492,7 @@ then
     error 3 "could not start orchestrator"
 fi
 
-wait_for_process ${network_retries} "orchestrator" "${master}" "${kvs_port}"
+wait_for_process ${network_retries} "orchestrator" "${kvs_host}" "${kvs_port}"
 ec=$?
 if [ $ec -ne 0 ]
 then
@@ -525,7 +521,7 @@ if $gpi_enabled ; then
         --daemonize \
         --pidfile "$state_dir/gpi-space.pid" \
         --gpi-mem "$gpi_mem" \
-        --kvs-host "${master}" --kvs-port "$kvs_port" \
+        --kvs-host "${kvs_host}" --kvs-port "${kvs_port}" \
         --log-host "${log_host}" --log-port "${log_port}" \
         --socket "${gpi_socket}"
 
@@ -608,7 +604,8 @@ function start_agent
         -n "${name}" \
         -m "${parent}" \
         -s "${state_dir}" \
-        -k "${master}:${kvs_port}" \
+        -k "${kvs_host}" \
+        -K "${kvs_port}" \
         -l "${log_host}:${log_port}" \
         -H "${sdpa_home}" \
         -g "${gui_host}:${gui_port}" &
@@ -677,7 +674,8 @@ function start_workers_for_capability
         argv+=(-c $num_per_node)
         argv+=(-n "$name")
         argv+=(-m "$parent")
-        argv+=(-k "$master:${kvs_port}")
+        argv+=(-k "${kvs_host}")
+        argv+=(-K "${kvs_port}")
         argv+=(-g "${gui_host}:${gui_port}")
         argv+=(-l "${log_host}:${log_port}")
         argv+=($caps_arg)
