sdpa: start scripts accept path to config file

diff --git a/sdpa/bin/pbs/start-drts b/sdpa/bin/pbs/start-drts
--- a/sdpa/bin/pbs/start-drts
+++ b/sdpa/bin/pbs/start-drts
@@ -22,6 +22,7 @@ kvs_url=
 count=
 capabilities=""
 state_dir="$HOME/.sdpa/state"
+config_file="$HOME/.sdpa/configs/sdpa.rc"
 logdir=
 shm_size=
 com_size=
@@ -47,6 +48,7 @@ usage: $(basename "$0") [options]
     -D daemonize
     -L logfile
     -s state-dir
+    -F config file
     -M shared memory size
     -B communication buffer size
 EOF
@@ -75,7 +77,7 @@ function to_bg ()
     /bin/kill -CONT "$pid"
 }
 
-while getopts ":hvfg:m:i:b:S:l:k:Dc:C:L:s:n:M:B:" opt; do
+while getopts ":hvfg:m:i:b:S:l:k:Dc:C:L:s:n:M:B:F:" opt; do
     case $opt in
         h)
             usage
@@ -131,6 +133,9 @@ while getopts ":hvfg:m:i:b:S:l:k:Dc:C:L:s:n:M:B:" opt; do
         s)
             state_dir="$OPTARG"
             ;;
+        F)
+            config_file="$OPTARG"
+            ;;
         n)
             name_prefix="$OPTARG"
             ;;
@@ -157,14 +162,19 @@ else
     exit 4
 fi
 
-if [ -z "$gui" ]
-then
-  gui="$(fhgcfg -f ~/.sdpa/configs/sdpa.rc -g sdpa.gui -v "$GUI_URL")"
+if [ ! -r "${config_file}" ] ; then
+    echo >&2 "config file '${config_file}' does not exist, aborting."
+    exit 4
 fi
 
-gpi_enabled="$(fhgcfg -f ~/.sdpa/configs/sdpa.rc -g gpi.enabled -v true)"
+if [ -z "$gui" ]
+then
+  gui=$(fhgcfg -f "${config_file}" -g sdpa.gui -v "$GUI_URL")
+fi
+
+gpi_enabled=$(fhgcfg -f "${config_file}" -g gpi.enabled -v true)
 if [ $backlog -lt 0 ] ; then
-    backlog=$(fhgcfg -f ~/.sdpa/configs/sdpa.rc -g plugin.drts.backlog -v 1)
+    backlog=$(fhgcfg -f "${config_file}" -g plugin.drts.backlog -v 1)
 fi
 
 if [ -z "$lib_path" ]
@@ -259,17 +269,15 @@ for p in $still_running ; do
     fi
 done
 
-# TODO: get those from the .sdpa/configs/sdpa.rc file, at least parts of it
-
 # config values (kernel)
-lazy="$(fhgcfg -f ~/.sdpa/configs/sdpa.rc -g kernel.lazy -v false)"
+lazy=$(fhgcfg -f "${config_file}" -g kernel.lazy -v false)
 if [ x"$lazy" = x"true" ] ; then
     cfg="$cfg -s kernel.load.lazy=1"
 else
     cfg="$cfg -s kernel.load.lazy=0"
 fi
 
-stateful="$(fhgcfg -f ~/.sdpa/configs/sdpa.rc -g sdpa.stateful -v false)"
+stateful=$(fhgcfg -f "${config_file}" -g sdpa.stateful -v false)
 if [ x"$stateful" = x"true" ] ; then
     cfg="$cfg -S ${state_dir}/state/kernel/$name"
 fi
@@ -281,7 +289,7 @@ cfg="$cfg -s plugin.kvs.host=$kvs_host"
 cfg="$cfg -s plugin.kvs.port=$kvs_port"
 
 # config values (logc plugin)
-logc_port=$(fhgcfg -f ~/.sdpa/configs/sdpa.rc -g plugin.logd.port -v "3456")
+logc_port=$(fhgcfg -f "${config_file}" -g plugin.logd.port -v "3456")
 logc_host=$(head -n 1 "${state_dir}/nodefile")
 cfg="$cfg -s plugin.logc.url=${logc_host}:${logc_port}"
 
@@ -289,21 +297,21 @@ cfg="$cfg -s plugin.logc.url=${logc_host}:${logc_port}"
 cfg="$cfg -s plugin.drts.name=$name"
 cfg="$cfg -s plugin.drts.master=$master"
 cfg="$cfg -s plugin.drts.backlog=$backlog"
-cfg="$cfg -s plugin.drts.max_reconnect_attempts=$(fhgcfg -f ~/.sdpa/configs/sdpa.rc -g plugin.drts.max_reconnect_attempts -v 128)"
+cfg="$cfg -s plugin.drts.max_reconnect_attempts=$(fhgcfg -f "${config_file}" -g plugin.drts.max_reconnect_attempts -v 128)"
 cfg="$cfg -s plugin.drts.capabilities=${capabilities}"
 
 # config values (gpi plugin)
 if [ -n "$gpi_socket" ] ; then
     cfg="$cfg -s plugin.gpi.socket=${gpi_socket}"
 fi
-cfg="$cfg -s plugin.gpi.startmode=$(fhgcfg -f ~/.sdpa/configs/sdpa.rc -g plugin.gpi.startmode -v wait)"
+cfg="$cfg -s plugin.gpi.startmode=$(fhgcfg -f "${config_file}" -g plugin.gpi.startmode -v wait)"
 
 if [ -z "$com_size" ] ; then
-    com_size=$(fhgcfg -f ~/.sdpa/configs/sdpa.rc -g plugin.gpi_compat.com_size -v 16777216)
+    com_size=$(fhgcfg -f "${config_file}" -g plugin.gpi_compat.com_size -v 16777216)
 fi
 
 if [ -z "$shm_size" ] ; then
-    shm_size=$(fhgcfg -f ~/.sdpa/configs/sdpa.rc -g plugin.gpi_compat.shm_size -v 536870912)
+    shm_size=$(fhgcfg -f "${config_file}" -g plugin.gpi_compat.shm_size -v 536870912)
 fi
 
 # config values (gpi_compat plugin)
@@ -316,7 +324,7 @@ cfg="$cfg -s plugin.gui.url=$gui"
 # config values (wfe plugin)
 cfg="$cfg -s plugin.wfe.library_path=${PC_LIBRARY_PATH}"
 
-plugins="$(fhgcfg -f ~/.sdpa/configs/sdpa.rc -g kernel.plugins)"
+plugins=$(fhgcfg -f "${config_file}" -g kernel.plugins)
 
 plugin_load_flags=""
 for p in $(echo $plugins | tr ',' ' '); do
diff --git a/sdpa/bin/pbs/start-gpi b/sdpa/bin/pbs/start-gpi
--- a/sdpa/bin/pbs/start-gpi
+++ b/sdpa/bin/pbs/start-gpi
@@ -20,6 +20,7 @@ log_host=
 log_port=
 verbose=false
 state_dir=~/.sdpa/state
+config_file="$HOME/.sdpa/configs/sdpa.rc"
 
 function usage ()
 {
@@ -46,57 +47,57 @@ EOF
 
 while getopts ":hd:x:gm:p:P:fDk:K:l:L:vs:" opt; do
     case $opt in
-	h)
-	    usage
-	    exit 0
-	    ;;
-	d)
-	    gpi_bin_path=$OPTARG
-	    ;;
-	x)
-	    gpi_exe=$OPTARG
-	    ;;
-	g)
-	    debug=true
-	    ;;
-	m)
-	    mem_size=$OPTARG
-	    ;;
-	p)
-	    gpi_port=$OPTARG
-	    ;;
-	P)
-	    pidfile=$OPTARG
-	    ;;
-	f)
-	    force=true
-	    ;;
-	D)
-	    daemonize=true
-	    ;;
-	k)
-	    kvs_host=$OPTARG
-	    ;;
-	K)
-	    kvs_port=$OPTARG
-	    ;;
-	l)
-	    log_host=$OPTARG
-	    ;;
-	L)
-	    log_port=$OPTARG
-	    ;;
-	v)
-	    verbose=true
-	    ;;
-	s)
-	    state_dir=$OPTARG
-	    ;;
-	\?)
-	    echo "invalid option: -$OPTARG" >&2
-	    echo "try: $0 -h" >&2
-	    exit 1
-	    ;;
+        h)
+            usage
+            exit 0
+            ;;
+        d)
+            gpi_bin_path=$OPTARG
+            ;;
+        x)
+            gpi_exe=$OPTARG
+            ;;
+        g)
+            debug=true
+            ;;
+        m)
+            mem_size=$OPTARG
+            ;;
+        p)
+            gpi_port=$OPTARG
+            ;;
+        P)
+            pidfile=$OPTARG
+            ;;
+        f)
+            force=true
+            ;;
+        D)
+            daemonize=true
+            ;;
+        k)
+            kvs_host=$OPTARG
+            ;;
+        K)
+            kvs_port=$OPTARG
+            ;;
+        l)
+            log_host=$OPTARG
+            ;;
+        L)
+            log_port=$OPTARG
+            ;;
+        v)
+            verbose=true
+            ;;
+        s)
+            state_dir=$OPTARG
+            ;;
+        \?)
+            echo "invalid option: -$OPTARG" >&2
+            echo "try: $0 -h" >&2
+            exit 1
+            ;;
     esac
 done
 
@@ -104,9 +105,9 @@ test -e "$state_dir/sdpa.env" && source "$state_dir/sdpa.env"
 
 if [ -z "$gpi_bin_path" ] ; then
     if [ -n "$GPI_PRIV_DIR" ] ; then
-	gpi_bin_path="$GPI_PRIV_DIR"
+        gpi_bin_path="$GPI_PRIV_DIR"
     else
-	gpi_bin_path=$(fhgcfg -f "$HOME/.sdpa/configs/sdpa.rc" -g gpi.priv_dir)
+        gpi_bin_path=$(fhgcfg -f "${config_file}" -g gpi.priv_dir)
     fi
 fi
 
@@ -133,8 +134,8 @@ else
     md_inst=$( md5sum "${gpi_bin_path}/${gpi_bin}" | cut -d ' ' -f 1 )
     md_cand=$( md5sum "${gpi_exe}" | cut -d ' ' -f 1 )
     if [ "$md_inst" != "$md_cand" ] ; then
-	log "candidate ${gpi_exe} is different than the one in ${gpi_bin_path}"
-	need_copy=true
+        log "candidate ${gpi_exe} is different than the one in ${gpi_bin_path}"
+        need_copy=true
     fi
 fi
 
@@ -145,68 +146,68 @@ fi
 if [ $need_copy = "true" -a $do_copy = "false" ] ; then
     read -t 5 -n 1 -p "Do you want me to copy \"$gpi_exe\" to \"$gpi_bin_path\"? [y/N] " ans
     case "$ans" in
-	y|Y)
-	    do_copy=true
-	    ;;
-	*)
-	    ;;
+        y|Y)
+            do_copy=true
+            ;;
+        *)
+            ;;
     esac
 fi
 
 if [ $do_copy = "true" ] ; then
     if [ ! -d "$gpi_bin_path" ] ; then
-	tmp=$( mkdir -p "$gpi_bin_path" 2>&1 )
-	if [ $? -ne 0 ] ; then
-	    log "could not create $gpi_bin_path: $tmp"
-	    exit 1
-	fi
+        tmp=$( mkdir -p "$gpi_bin_path" 2>&1 )
+        if [ $? -ne 0 ] ; then
+            log "could not create $gpi_bin_path: $tmp"
+            exit 1
+        fi
     fi
     if [ -w "$gpi_bin_path" ] ; then
-	test -e "${gpi_bin_path}/${gpi_bin}" && {
-	    log "I: creating backup of old ${gpi_bin}"
-	    mv -f "${gpi_bin_path}/${gpi_bin}" "${gpi_bin_path}/${gpi_bin}~"
-	}
-	cp "${gpi_exe}" "${gpi_bin_path}/${gpi_bin}" && {
-	    log "I: installed new ${gpi_bin} in ${gpi_bin_path}/${gpi_bin}"
-	} || {
-	    log "W: could not update ${gpi_bin} in ${gpi_bin_path}/${gpi_bin}"
-	}
-	chmod ug=rx,o= "${gpi_bin_path}/${gpi_bin}"
+        test -e "${gpi_bin_path}/${gpi_bin}" && {
+            log "I: creating backup of old ${gpi_bin}"
+            mv -f "${gpi_bin_path}/${gpi_bin}" "${gpi_bin_path}/${gpi_bin}~"
+        }
+        cp "${gpi_exe}" "${gpi_bin_path}/${gpi_bin}" && {
+            log "I: installed new ${gpi_bin} in ${gpi_bin_path}/${gpi_bin}"
+        } || {
+            log "W: could not update ${gpi_bin} in ${gpi_bin_path}/${gpi_bin}"
+        }
+        chmod ug=rx,o= "${gpi_bin_path}/${gpi_bin}"
     else
-	log "W: privileged path $gpi_bin_path does not exist, or i am not allowed to write to it!"
+        log "W: privileged path $gpi_bin_path does not exist, or i am not allowed to write to it!"
     fi
 fi
 
 if [ -x "$gpi_bin_path/$gpi_bin" ] ; then
     cmdline=
     if $debug ; then
-	cmdline="gdb -ex run --args $cmdline"
+        cmdline="gdb -ex run --args $cmdline"
     fi
     cmdline="$cmdline ${gpi_bin_path}/${gpi_bin}"
 
     if $verbose ; then
-	cmdline="$cmdline --log-level TRACE"
+        cmdline="$cmdline --log-level TRACE"
     fi
     if $daemonize && ! $debug ; then
-	cmdline="$cmdline --daemonize"
+        cmdline="$cmdline --daemonize"
     fi
     if test -n "$mem_size" ; then
-	cmdline="$cmdline --gpi-mem $mem_size"
+        cmdline="$cmdline --gpi-mem $mem_size"
     fi
     if test -n "$pidfile" ; then
-	cmdline="$cmdline --pidfile $pidfile"
+        cmdline="$cmdline --pidfile $pidfile"
     fi
     if test -n "$kvs_host" ; then
-	cmdline="$cmdline --kvs_host $kvs_host"
+        cmdline="$cmdline --kvs_host $kvs_host"
     fi
     if test -n "$kvs_port" ; then
-	cmdline="$cmdline --kvs_host $kvs_port"
+        cmdline="$cmdline --kvs_host $kvs_port"
     fi
     if test -n "$log_host" ; then
-	cmdline="$cmdline --kvs_host $log_host"
+        cmdline="$cmdline --kvs_host $log_host"
     fi
     if test -n "$log_port" ; then
-	cmdline="$cmdline --kvs_host $log_port"
+        cmdline="$cmdline --kvs_host $log_port"
     fi
 
     log "executing $cmdline"
