pbs: wait for all gpi processes to appear before continuing

diff --git a/sdpa/bin/pbs/start-sdpa b/sdpa/bin/pbs/start-sdpa
--- a/sdpa/bin/pbs/start-sdpa
+++ b/sdpa/bin/pbs/start-sdpa
@@ -531,6 +531,29 @@ if $gpi_enabled ; then
         "${sdpa}" -s "${state_dir}" stop
         error 3 "could not start gpi-space"
     fi
+
+    # HACK: GPI does _not_ use that nodefile. We can just hope that
+    # the user specified the same as GPI uses!
+    for host in $(sort -u "${nodefile}")
+    do
+      echo -n "I: Checking for virtual memory socket on '$host' "
+      ssh "$host" "for ((i=0; i < $((10 * ${network_retries})); ++i)); do \
+                     if [ ! -e ${gpi_socket} ]; then \
+                       echo -n .; \
+                       sleep 0.1; \
+                     else \
+                       exit 0;
+                     fi \
+                   done; \
+                   exit 1"
+      if [ $? -ne 0 ]
+      then
+        echo "FAILED"
+        error 3 "could not start virtual memory layer: socket failed to on '$host' appear after ${network_retries} seconds"
+      else
+        echo "OK"
+      fi
+    done
 fi
 
 # for each capability:
