pbs: chg: start-drts and start-agent always expect gui-url

diff --git a/sdpa/bin/pbs/start-agent b/sdpa/bin/pbs/start-agent
--- a/sdpa/bin/pbs/start-agent
+++ b/sdpa/bin/pbs/start-agent
@@ -99,7 +99,8 @@ fi
 
 if [ -z "$gui" ]
 then
-  gui=$(fhgcfg -f "${config_file}" -g sdpa.gui)
+    echo >&2 "gui url is required, please specify -g"
+    exit 4
 fi
 
 if [ -z "$logdir" ]
diff --git a/sdpa/bin/pbs/start-drts b/sdpa/bin/pbs/start-drts
--- a/sdpa/bin/pbs/start-drts
+++ b/sdpa/bin/pbs/start-drts
@@ -159,7 +159,8 @@ fi
 
 if [ -z "$gui" ]
 then
-  gui=$(fhgcfg -f "${config_file}" -g sdpa.gui -v "$GUI_URL")
+    echo >&2 "gui url is required, please specify -g"
+    exit 4
 fi
 
 if [ -z "$kvs_url" ]
