mon: no global workdir anymore
	- actions have parameters
	- workdir is passed through several incarnations

diff --git a/gspcmon/hooks/add b/gspcmon/hooks/add
--- a/gspcmon/hooks/add
+++ b/gspcmon/hooks/add
@@ -1,12 +1,34 @@
 #!/bin/bash
 
-if [ ! -d "$GSPCMON_WORKDIR" ]
+workdir=
+nodes=()
+
+for arg
+do
+    case "$arg" in
+        node=*)
+            nodes+=(${arg#*=})
+            ;;
+        workdir=*)
+            workdir=${arg#*=}
+            ;;
+        walltime=*)
+            walltime=${arg#*=}
+            ;;
+        *)
+            echo >&2 "$(basename $0): invalid argument: $arg"
+            exit 1
+            ;;
+    esac
+done
+
+if [ -z "${workdir}" ]
 then
-    echo >&2 "workdir is invalid: $GSPCMON_WORKDIR"
+    echo >&2 "workdir was not set"
     exit 77
 fi
 
-for node
+for node in ${nodes[@]}
 do
-    echo "$node 0 inuse $node is now in use"
+    echo "$node 0 inuse $node is now in use ($workdir)"
 done
diff --git a/gspcmon/hooks/status b/gspcmon/hooks/status
--- a/gspcmon/hooks/status
+++ b/gspcmon/hooks/status
@@ -1,29 +1,72 @@
 #!/bin/bash
 
-transitions=("calc" "reduce" "mgmt")
-free_states=("free" "free/reserved" "addable" "addable/reserved")
+workdir=
+nodes=()
 
-master=
-
-for node
+for arg
 do
+    case "$arg" in
+        node=*)
+            nodes+=(${arg#*=})
+            ;;
+        workdir=*)
+            workdir=${arg#*=}
+            ;;
+        *)
+            echo >&2 "$(basename $0): invalid argument: $arg"
+            exit 1
+            ;;
+    esac
+done
+
+transitions=("calc" "reduce" "mgmt")
+
+if [ -z "$workdir" ]
+then
+    master=
+    free_states=("free" "free/reserved")
+else
+    n=$(( RANDOM % ${#nodes[@]} ))
+    master=${nodes[$n]}
+    free_states=("addable" "addable/reserved")
+fi
+
+for node in ${nodes[@]}
+do
+    t=$(( RANDOM % ${#transitions[@]} ))
+    trans=${transitions[${t}]}
+
+    if [ "$node" = "$master" ]
+    then
+        echo "$node 0 master $trans"
+        continue
+    fi
+
     r=$(( RANDOM % 1000))
 
     if [ $r -lt 10 ] ; then
         echo "$node 0 down"
     elif [ $r -lt 50 ] ; then
         echo "$node 0 unavailable"
-    elif [ $r -lt 200 ] ; then
-        t=$(( RANDOM % ${#free_states[@]} ))
-        echo "$node 0 ${free_states[${t}]}"
     else
-        t=$(( RANDOM % ${#transitions[@]} ))
+        t=$(( RANDOM % ${#free_states[@]} ))
+        f="${free_states[${t}]}"
+
         if [ -z "$master" ]
         then
-            master="$node"
-            echo "$node 0 master ${transitions[${t}]}"
+            if [ $r -lt 500 ]
+            then
+                echo "$node 0 unavailable"
+            else
+                echo "$node 0 ${f}"
+            fi
         else
-            echo "$node 0 inuse ${transitions[${t}]}"
+            if [ $r -lt 500 ]
+            then
+                echo "$node 0 $f"
+            else
+                echo "$node 0 inuse ${trans}"
+            fi
         fi
     fi
 done
diff --git a/gspcmon/hooks/stop b/gspcmon/hooks/stop
--- a/gspcmon/hooks/stop
+++ b/gspcmon/hooks/stop
@@ -1,9 +1,31 @@
 #!/bin/bash
 
-free_states=("free" "free/reserved")
+workdir=
+nodes=()
 
-for node
+for arg
 do
-    t=$(( RANDOM % ${#free_states[@]} ))
-    echo "$node 0 ${free_states[${t}]} is not in use anymore"
+    case "$arg" in
+        node=*)
+            nodes+=(${arg#*=})
+            ;;
+        workdir=*)
+            workdir=${arg#*=}
+            ;;
+        *)
+            echo >&2 "$(basename $0): invalid argument: $arg"
+            exit 1
+            ;;
+    esac
+done
+
+if [ -z "${workdir}" ]
+then
+    echo >&2 "already stopped"
+    exit 77
+fi
+
+for node in ${nodes[@]}
+do
+    echo "$node 0 free now free again"
 done
