mon: as an example, action "add" refused to work, when no WORKDIR is set

diff --git a/gspcmon/hooks/add b/gspcmon/hooks/add
--- a/gspcmon/hooks/add
+++ b/gspcmon/hooks/add
@@ -1,5 +1,11 @@
 #!/bin/bash
 
+if [ ! -d "$GSPCMON_WORKDIR" ]
+then
+    echo >&2 "workdir is invalid: $GSPCMON_WORKDIR"
+    exit 77
+fi
+
 for node
 do
     echo "$node 0 inuse $node is now in use"
