fixed nodefile handling and gpi config path
From: Alexander Petry <alexander.petry@itwm.fraunhofer.de>

git-svn-id: https://svn.itwm.fhg.de/svn/SDPA@4019 c3adf61f-8968-0410-94d0-83abfdf586cf

diff --git a/trunk/sdpa/trunk/bin/pbs/boot-nre b/trunk/sdpa/trunk/bin/pbs/boot-nre
--- a/trunk/sdpa/trunk/bin/pbs/boot-nre
+++ b/trunk/sdpa/trunk/bin/pbs/boot-nre
@@ -1,53 +1,51 @@
 #!/bin/sh
 
-if [ -r ~/.init-screen.env ]; then
-    source ~/.init-screen.env
-fi
+source ~/.init-screen.env
 
-if [ ! -r "$PBS_NODEFILE" ]; then
-  echo "E: must be run on head node"
-  exit 2
+if [ ! -r "$SDPA_NODEFILE" ]; then
+    log "I cannot access the nodefile: $SDPA_NODEFILE"
+    exit 2
 fi
 
 ps aux | grep -q "[s]dpa-gpi"
 if [ $? -ne 0 ]; then
-  echo "W: GPI is not running, checking for fvm!"
-  ps aux | grep -q "[f]vm_sdpa_standalone"
-  if [ $? -ne 0 ] ; then
-	echo "F: FVM is not running, please start either sdpa-gpi or fvm_sdpa_standalone!"
+    log "W: GPI is not running, checking for fvm!"
+    ps aux | grep -q "[f]vm_sdpa_standalone"
+    if [ $? -ne 0 ] ; then
+	log "F: FVM is not running, please start either sdpa-gpi or fvm_sdpa_standalone!"
 	exit 2
-  fi
+    fi
 fi
 
-node_max=$( uniq $PBS_NODEFILE | wc -l )
+node_max=$( uniq $SDPA_NODEFILE | wc -l )
 nodes=$( echo $( seq 1 $node_max ) )
 if [ $# -lt 1 ]; then
-  echo "booting all NREs..."
+    log "booting all NREs..."
 else
-  nodes=$@
+    nodes=$@
 fi
 
 bunch_size=16
 count=0
 for node_num in $nodes; do
-  if [ $node_num -lt 1 -o $node_num -gt "$node_max" ]; then
+    if [ $node_num -lt 1 -o $node_num -gt "$node_max" ]; then
 	echo "W: ignoring node number $node_num: out of range: must be within [1,$node_max]"
-    continue
-  fi
+	continue
+    fi
 
-  count=$(( count + 1 ))
+    count=$(( count + 1 ))
 
-  node_name=$( uniq $PBS_NODEFILE | tail -n +$node_num | head -n 1 )
-  rm -f "$SDPA_LOG_DIR/nre.$node_name.log"
-  rm -f "$SDPA_LOG_DIR/pc.$node_name.log"
-  rank=$(( $node_num - 1 ))
+    node_name=$( uniq $SDPA_NODEFILE | tail -n +$node_num | head -n 1 )
+    rm -f "$SDPA_LOG_DIR/nre.$node_name.log"
+    rm -f "$SDPA_LOG_DIR/pc.$node_name.log"
+    rank=$(( $node_num - 1 ))
 
-  log "starting nre on $node_name (rank: $rank)..."
+    log "starting nre on $node_name (rank: $rank)..."
 
-  ssh -x $node_name start-nre $rank >/dev/null 2>&1 &
-  if [ $count -gt $bunch_size ] ; then
-      wait
-      count=0
-  fi
+    ssh -x $node_name start-nre $rank >/dev/null 2>&1 &
+    if [ $count -gt $bunch_size ] ; then
+	wait
+	count=0
+    fi
 done
 wait
diff --git a/trunk/sdpa/trunk/bin/pbs/kill-nre b/trunk/sdpa/trunk/bin/pbs/kill-nre
--- a/trunk/sdpa/trunk/bin/pbs/kill-nre
+++ b/trunk/sdpa/trunk/bin/pbs/kill-nre
@@ -1,13 +1,16 @@
-#!/bin/sh
-if [ ! -r "$PBS_NODEFILE" ]; then
-  echo "E: must be run on head node"
-  exit 2
+#!/bin/bash
+
+source ~/.init-screen.env
+
+if [ ! -r "$SDPA_NODEFILE" ]; then
+    log "Cannot access nodefile: $SDPA_NODEFILE"
+    exit 2
 fi
 
-node_max=$( uniq $PBS_NODEFILE | wc -l )
+node_max=$( uniq $SDPA_NODEFILE | wc -l )
 nodes=$( echo $( seq 1 $node_max ) )
 if [ $# -lt 1 ]; then
-  echo "killing all NREs..."
+    log "killing all NREs..."
 else
   nodes=$@
 fi
@@ -21,8 +24,8 @@ for node_num in $nodes; do
 
   count=$(( count + 1 ))
 
-  node_name=$( uniq $PBS_NODEFILE | tail -n +$node_num | head -n 1 )
-  echo "killing nre on $node_name..."
+  node_name=$( uniq $SDPA_NODEFILE | tail -n +$node_num | head -n 1 )
+  log "killing nre on $node_name..."
   ssh -x $node_name killall nre-pcd >/dev/null 2>&1 &
   ssh -x $node_name killall nre >/dev/null 2>&1 &
   if [ $count -gt $bunch_size ] ; then
