added a simple node-check script that checks basic availability/functionality of allocated nodes
git-svn-id: https://svn.itwm.fhg.de/svn/SDPA@3345 c3adf61f-8968-0410-94d0-83abfdf586cf

diff --git a/trunk/sdpa/trunk/bin/pbs/init-screen b/trunk/sdpa/trunk/bin/pbs/init-screen
--- a/trunk/sdpa/trunk/bin/pbs/init-screen
+++ b/trunk/sdpa/trunk/bin/pbs/init-screen
@@ -39,6 +39,13 @@ if [ -r "$PBS_NODEFILE" ]; then
 	echo "Running on the initial master node..."
 	on_master=1
 	master="$node_name"
+	echo "Checking node availability..."
+	check-nodes
+	rc=$?
+	if [[ $rc -ne 0 ]]; then
+	  echo "$rc node(s) failed the availability test, giving up!"
+	  exit $rc
+	fi
 else
 	echo "Running on slave $node_name..."
 fi
