working to remove hard dependency to PBS
From: Alexander Petry <alexander.petry@itwm.fraunhofer.de>

git-svn-id: https://svn.itwm.fhg.de/svn/SDPA@4011 c3adf61f-8968-0410-94d0-83abfdf586cf

diff --git a/trunk/sdpa/trunk/bin/pbs/init-screen b/trunk/sdpa/trunk/bin/pbs/init-screen
--- a/trunk/sdpa/trunk/bin/pbs/init-screen
+++ b/trunk/sdpa/trunk/bin/pbs/init-screen
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 # get the list of nodes
 nodes=
@@ -20,7 +20,8 @@ usage $0 [-h|--help] [node...]
 
 environment variables:
 	export IN_INIT_SCREEN="$IN_INIT_SCREEN"
-	export PBS_O_HOST="$PBS_O_HOST"
+	#export PBS_O_HOST="$PBS_O_HOST"
+        export SDPA_SCRATCH="$SDPA_SCRATCH"
 	export SDPA_GUI="$SDPA_GUI"
 	export SDPA_MASTER="$SDPA_MASTER"
 	export FHGLOG_to_console="$FHGLOG_to_console"
@@ -28,97 +29,160 @@ environment variables:
 	export FHGLOG_threaded="$FHGLOG_threaded"
         export KVS_URL="$KVS_URL"
 EOF
-    exit 1
+    exit 0
 	;;
   *)
 	# ignore
 	;;
 esac
 
-test -d /scratch/$USER/sdpa || mkdir -p /scratch/$USER/sdpa
+function log ()
+{
+    echo "$@" >/dev/stderr
+}
+
+if [ ! -d "${SDPA_SCRATCH}" ] ; then
+    log "W: SDPA_SCRATCH is not defined, please enter it now or export it before!"
+    read -p "type in scratch dir to use: " scratch_dir
+
+    if [ -z "$scratch_dir" ] ; then
+	return 1
+    fi
+
+    if [ ! -d "$scratch_dir" ] ; then
+	read -n 1 -p "W: $scratch_dir does not exist, shall i create it [y/N]? " do_create
+	case "$do_create" in
+	    y|Y)
+		mkdir -p "$scratch_dir"
+		;;
+	    *)
+		log "bye."
+		return 1
+		;;
+	esac
+    fi
+    if [ ! -d "$scratch_dir" ] ; then
+	log "bye."
+	return 1
+    fi
+    SDPA_SCRATCH="$scratch_dir"
+fi
+
+if [ -z "$SDPA_SCRATCH" ] ; then
+    log "# E: SDPA_SCRATCH is still undefined, Bye."
+    return 1
+fi
+
+if [ -z "$SDPA_NODEFILE" ] ; then
+    export SDPA_NODEFILE="$HOME/.init-screen.nodes"
+    log "# W: SDPA_NODEFILE is not defined, asuming $SDPA_NODEFILE"
+fi
+
+if [ ! -r "$SDPA_NODEFILE" ] ; then
+    :
+fi
 
 if [ -r "$PBS_NODEFILE" ]; then
-	echo "Running on the initial master node..."
+	log "Running on the initial master node..."
 	on_master=1
 	master="$node_name"
 else
-	echo "Running on slave $node_name..."
+	log "Running on slave $node_name..."
 fi
 
 TABLE="$HOME/.init-screen.tab"
 if [ $on_master -eq 1 ]; then
 	if [ -r "$TABLE" ]; then
 	  if grep -q "$master" "$TABLE"; then
-		echo "It seems, that there is already another screen environment running."
-		echo
-		echo "hint:"
-		echo "   possibly running on: `cat ${TABLE} | awk '{print $3}'`"
-		echo
-		echo "Please remove the entry from ${TABLE} and retry."
-		exit 1
+		log "# It seems, that there is already another screen environment running."
+		log "#"
+		log "# hint:"
+		log "#   possibly running on: `cat ${TABLE} | awk '{print $3}'`"
+		log "#"
+		log "# Please remove the entry from ${TABLE} and retry."
 	  fi
 	fi
 
-	echo "Checking node availability..."
-	check-nodes
-	rc=$?
-	if [[ $rc -ne 0 ]]; then
-	  echo "$rc node(s) failed the availability test, giving up!"
-	  exit $rc
-	fi
+#	echo "Checking node availability..."
+#	check-nodes
+#	rc=$?
+#	if [[ $rc -ne 0 ]]; then
+#	  log "$rc node(s) failed the availability test, giving up!"
+#	  exit $rc
+#	fi
 
 	tmp=`cat $PBS_NODEFILE | sort -u | grep -v "$master" | sort -n`
 	tmp=`echo $master $tmp`
-	echo "${PBS_JOBCOOKIE} = $tmp" > "${TABLE}"
-	# distcc support
-	if [ -d $HOME/.distcc ]; then
-	  rm -f $HOME/.distcc/hosts
-	  # use ssh for now
-	  distcc_hosts=
-	  for n in $tmp; do
-		distcc_hosts="@${n} $distcc_hosts"
-	  done
-	  echo "$distcc_hosts" > $HOME/.distcc/hosts
-	fi
+	echo "${PS_JOBCOOKIE} = $tmp" > "${TABLE}"
 
 	env_file="$HOME/.init-screen.env"
 
-	echo "clearing .init-screen.env..."
+	log "clearing .init-screen.env..."
 	rm -f "$env_file"
-	echo "writing environment info to $env_file..."
+	log "writing environment info to $env_file..."
 
 	test -d "$HOME/.sdpa/data" || mkdir -p "$HOME/.sdpa/data"
 
+	SDPA_LOG_DIR="$SDPA_SCRATCH/log"
+	test -d "$SDPA_LOG_DIR" || mkdir -p "$SDPA_LOG_DIR"
+
 	cat > "$env_file" <<EOF
+#
+# init screen internal
+#
 export IN_INIT_SCREEN="yes"
-export PBS_O_HOST="$PBS_O_HOST"
+#export PBS_O_HOST="$PBS_O_HOST"
+test -r "$HOME/.init-screen.mod" && source "$HOME/.init-screen.mod"
+#
+# sdpa config
+#
 export SDPA_MASTER="$master"
+export SDPA_SCRATCH="$SDPA_SCRATCH"
+export SDPA_LOG_DIR="$SDPA_SCRATCH/log"
+#
+# logging config
+#
 export FHGLOG_to_server="$master"
-export FHGLOG_to_console="false"
+unset  FHGLOG_to_console
 export FHGLOG_threaded="false"
 export FHGLOG_level="WARN"
+#
+# key value store config
+#
 export KVS_URL="$master:2439"
 export KVS_STORE="$HOME/.sdpa/data/kvs.dat"
-# user config follows (may override above values, please be careful)
+#
+# user config follows (may override above values, please be careful!)
+#
 test -r "$HOME/.init-screen.rc" && source "$HOME/.init-screen.rc"
 EOF
 
 	if [ ! -r "$HOME/.init-screen.rc" ]; then
-	    echo "creating default .init-screen.rc file..."
+	    log "creating default .init-screen.rc file..."
 	    cat > "$HOME/.init-screen.rc" <<EOF
 export PC_LIBRARY_PATH="\$HOME/.sdpa/modules"
 export PC_MODULE_DATA="\$HOME/.sdpa/moddata"
 EOF
 	fi
-
-	source "$env_file"
+	cat > "$HOME/.init-screen.mod" <<EOF
+#!/bin/bash
+#
+# helper function definitions
+#
+# log <message to be logged>
+function log ()
+{
+  echo "$@" >/dev/stderr
+  test -x `which fhglogc` && fhglogc -t "$0" -p 2 -m "$@"
+}
+EOF
 fi
 
 if [ $# -gt 0 ]; then
 	nodes=$@
 else
 	if [ -r "$PBS_NODEFILE" ]; then
-		echo "using nodes from $PBS_NODEFILE"
+		log "using nodes from $PBS_NODEFILE"
 		nodes=`cat $PBS_NODEFILE | sort -u | grep -v "$master" | sort -n`
 		nodes=`echo $master $nodes`
 		rename_master=1
@@ -130,7 +194,7 @@ else
 fi
 
 if [ -z "$nodes" ]; then
-	echo "Nothing to do"
+	log "Nothing to do"
 	exit 0
 fi
 
@@ -138,17 +202,17 @@ headnode="$PBS_O_HOST"
 
 if [ $start_fhglog -eq 1 ]; then
 #	killall fhglogd
-	echo "starting log-server on master node"
+	log "starting log-server on master node"
 	ssh -Y -t "$headnode" screen -D -RR -X "screen -t log ssh -Y -t $master" # fhglogd"
 fi
 
 if [ $start_kvs -eq 1 ]; then
-	echo "starting kvs-daemon on master node"
+	log "starting kvs-daemon on master node"
 	ssh -Y -t "$headnode" screen -D -RR -X "screen -t kvs ssh -Y -t $master" # fhgkvsd
 fi
 
 if [ $start_gpi -eq 1 ]; then
-	echo "starting gpi on master node"
+	log "starting gpi on master node"
 	ssh -Y -t "$headnode" screen -D -RR -X "screen -t gpi ssh -Y -t $master"
 	ssh -Y -t "$headnode" screen -D -RR -X "screen -t orch ssh -Y -t $master"
 	ssh -Y -t "$headnode" screen -D -RR -X "screen -t agg ssh -Y -t $master"
@@ -156,7 +220,7 @@ if [ $start_gpi -eq 1 ]; then
 fi
 
 if [ -z "$headnode" ]; then
-	echo "I don't know what my headnode is"
+	log "I don't know what my headnode is"
 	exit 1
 fi
 
@@ -164,28 +228,23 @@ numnodes=`echo $nodes | wc -w`
 maxnodes=10
 
 if [ $numnodes -gt $maxnodes ]; then
-	echo -n "do you really want to start screen sessions on $numnodes nodes (configured maximum=$maxnodes)? [y/N]: "
-	read answer
+	read -n 1 -p "Do you really want to start screen sessions on $numnodes nodes (configured maximum=$maxnodes)? [y/N]: " answer
 	case "$answer" in
-		y|Y|yes|Yes)
+		y|Y)
 			echo "ok, I'll do as you whish"
 			;;
 		*)
 			echo "Puh."
-			exit 0
+			return 0
 			;;
 	esac
 fi
-echo "going to start screen session on nodes:" $nodes
-
-echo -n 'starting sessions...'
+log "going to start screen session on nodes:" $nodes
 for n in $nodes; do
 	title="$n"
-
 	if [ $rename_master -eq 1 -a x"$n" == x"$master" ]; then
 		title="master:$n"
 	fi
-	echo -n " $n"
 	if [ x"$n" == x"$master" ]; then
 		ssh -Y -t "$headnode" screen -D -RR -X "screen -t $title ssh -Y -t $n"
 		ssh -Y -t "$headnode" screen -D -RR -X "screen -t $n ssh -Y -t $n" &
@@ -194,9 +253,11 @@ for n in $nodes; do
 	fi
 done
 wait
-echo
+echo "# Please execute the following commands:"
+echo "source $HOME/.init-screen.env"
+echo "trap \"rm $HOME/.init-screen.nodes\" EXIT"
 
 if [ $switch_to_master -eq 1 ]; then
-	echo "switching to master-node screen"
+	log "# switching to master-node screen"
 	ssh -Y -t "$headnode" screen -X select master
 fi
