smaller fixes in init-screen, environment variable SCREEN_SOCKET support started

diff --git a/trunk/sdpa/trunk/bin/pbs/init-screen b/trunk/sdpa/trunk/bin/pbs/init-screen
--- a/trunk/sdpa/trunk/bin/pbs/init-screen
+++ b/trunk/sdpa/trunk/bin/pbs/init-screen
@@ -1,6 +1,11 @@
 #!/bin/bash
 
-init_screen_ver=4
+init_screen_ver=5
+env_file="$HOME/.init-screen.env"
+tab_file="$HOME/.init-screen.tab"
+rc_file="$HOME/.init-screen.rc"
+cfg_file="$HOME/.init-screen.cfg"
+
 test -r "$HOME/.init-screen.cfg" && source "$HOME/.init-screen.cfg"
 
 head_node="${SDPA_HEAD_NODE}"
@@ -14,7 +19,7 @@ log_dir="$SDPA_LOG_DIR"
 temp_dir="$SDPA_TEMP_DIR"
 gui_url="$SDPA_GUI"
 gpi_priv_dir="$GPI_PRIV_DIR"
-screen_name=
+screen_name="$SCREEN_SOCKET"
 
 function usage ()
 {
@@ -58,7 +63,7 @@ to execute  binary files. It should point  to a directory you  have write access
 to.
 
 EOF
-    read -p "  GPI priviledged directory to use [$gpi_priv_dir]: " new_gpi_priv_dir
+    read -e -p "  GPI priviledged directory to use [$gpi_priv_dir]: " new_gpi_priv_dir
     if [ -n "$new_gpi_priv_dir" ] ; then
 	gpi_priv_dir="$new_gpi_priv_dir"
     fi
@@ -73,7 +78,7 @@ that is shared among all nodes. I will create a "log" directory within that into
 which all components are going to log.
 
 EOF
-    read -p "  scratch directory to use [$scratch_dir]: " new_scratch_dir
+    read -e -p "  scratch directory to use [$scratch_dir]: " new_scratch_dir
     if [ -n "$new_scratch_dir" ] ; then
 	scratch_dir="$new_scratch_dir"
     fi
@@ -89,7 +94,7 @@ This  directory  should point  to  a  path that  is  local  to  each node,  like
 some executions.
 
 EOF
-    read -p "  temporary directory to use [$temp_dir]: " new_temp_dir
+    read -e -p "  temporary directory to use [$temp_dir]: " new_temp_dir
     if [ -n "$new_temp_dir" ] ; then
 	temp_dir="$new_temp_dir"
     fi
@@ -99,13 +104,13 @@ EOF
 
 =====   GUI configuration  ====
 
-Now I  need a host:ip  string on which  the graphical monitor interface  will be
-running.  It does not  have to  run all  the time,  but if  you want  to monitor
+Now I need a 'host:port' string on which the graphical monitor interface will be
+running.  It  does not  have to run  all the  time, but if  you want  to monitor
 activities, I need to know that location. Please make sure that nobody else uses
 this location.
 
 EOF
-    read -p "  location of the monitor gui (host:ip) [$gui_url]: " new_gui_url
+    read -e -p "  location of the monitor gui (host:port) [$gui_url]: " new_gui_url
     if [ -n "$new_gui_url" ] ; then
 	gui_url="$new_gui_url"
     fi
@@ -131,7 +136,7 @@ bind ^X
 vbell off
 
 EOF
-	read -n 1 -p "  Shall I create this file now? [Y/n] " create_screenrc
+	read -e -n 1 -p "  Shall I create this file now? [Y/n] " create_screenrc
 	case "$create_screenrc" in
 	    n|N)
 		;;
@@ -164,6 +169,7 @@ export SDPA_LOG_DIR="$log_dir"
 export SDPA_TEMP_DIR="$temp_dir"
 export SDPA_GUI="$gui_url"
 export GPI_PRIV_DIR="$gpi_priv_dir"
+export PC_LIBRARY_PATH="$HOME/.sdpa/modules:$PC_LIBRARY_PATH"
 EOF
 
     cat <<EOF
@@ -186,7 +192,7 @@ function print_load_instructions ()
 {
 # please pass the following to the 'eval' function
      cat <<EOF
-if test -r ~/.init-screen.tab ; then if grep -q "\$(hostname -s)" ~/.init-screen.tab ; then if test -r ~/.init-screen.env ; then source ~/.init-screen.env; fi; fi; fi
+if test -r "${tab_file}" ; then if grep -q "\$(hostname -s)" "${tab_file}" ; then if test -r "${env_file}" ; then source "${env_file}"; fi; fi; fi
 EOF
 }
 
@@ -202,8 +208,8 @@ while getopts ":hcClf:n:s:" opt; do
 	    ;;
 	C)
 	    echo "clearing state files..." >&2
-	    rm -f ~/.init-screen.tab
-	    rm -f ~/.init-screen.env
+	    rm -f "${tab_file}"
+	    rm -f "${env_file}"
 	    echo "please logout and reinitialize now"
 	    exit 0
 	    ;;
@@ -232,6 +238,60 @@ function log ()
     echo "$@" >&2
 }
 
+function sanity_check_directories ()
+{
+    # GPI priviledged directory
+    if [ ! -d "$gpi_priv_dir" ] ; then
+	log "W: priviledged GPI directory ($gpi_priv_dir) does not exist!"
+	tmp=$( mkdir -p "$gpi_priv_dir" 2>&1 )
+	if [ $? -ne 0 ] ; then
+	    log "E: could not create $gpi_priv_dir: $tmp"
+	    return 1
+	fi
+    else
+	if [ ! -w "$gpi_priv_dir" ] ; then
+	    log "W: you are not permitted to write to the priviledged GPI directory."
+	    log "I:     dir: $gpi_priv_dir"
+	fi
+    fi
+
+    # sanity check for scratch directory
+    if [ -z "$scratch_dir" ] ; then
+	log "W: scrach_dir is not defined, please export SDPA_SCRATCH_DIR or put a definition in ~/.init-screen.cfg"
+	read -e -n 1 -p "scratch dir to use: " scratch_dir
+    fi
+
+    if [ ! -d "${scratch_dir}" ] ; then
+	read -e -n 1 -p "W: $scratch_dir does not exist, shall i create it for you [y/N]? " do_create
+	case "$do_create" in
+	    y|Y)
+		if ! mkdir -p "$scratch_dir" ; then
+		    log "E: could not create directory!"
+		    return 1
+		fi
+		;;
+	    *)
+		log "bye."
+		return 1
+		;;
+	esac
+    fi
+
+    if [ ! -d "${scratch_dir}" -o ! -w "${scratch_dir}" ] ; then
+	log "scratch-dir ${scratch_dir} still does not exist or cannot be written do, giving up" >&2
+	return 1
+    fi
+
+    if [ ! -d "$log_dir" ] ; then
+	mkdir -p "$log_dir"
+    fi
+
+    if [ ! -d "$HOME/.sdpa/modules" ] ; then
+	mkdir -p "$HOME/.sdpa/modules"
+    fi
+    return 0
+}
+
 if [ ! -e "$HOME/.init-screen.cfg" ] ; then
     log "E: \"$HOME/.init-screen.cfg\" does not exist, please run `basename $0` -c to create one."
     exit 1
@@ -253,50 +313,9 @@ if [ ! -e "$HOME/.sdpa/configs/sdpa-gpi.cfg" ] ; then
     exit 1
 fi
 
-# GPI priviledged directory
-if [ ! -d "$gpi_priv_dir" ] ; then
-    log "W: priviledged GPI directory ($gpi_priv_dir) does not exist!"
-    tmp=$( mkdir -p "$gpi_priv_dir" 2>&1 )
-    if [ $? -ne 0 ] ; then
-	log "E: could not create $gpi_priv_dir: $tmp"
-	exit 1
-    fi
-else
-    if [ ! -w "$gpi_priv_dir" ] ; then
-	log "W: you are not permitted to write to the priviledged GPI directory."
-	log "I:     dir: $gpi_priv_dir"
-    fi
-fi
-
-# sanity check for scratch directory
-if [ -z "$scratch_dir" ] ; then
-    log "W: scrach_dir is not defined, please export SDPA_SCRATCH_DIR or put a definition in ~/.init-screen.cfg"
-    read -n 1 -p "scratch dir to use: " scratch_dir
-fi
-
-if [ ! -d "${scratch_dir}" ] ; then
-    read -n 1 -p "W: $scratch_dir does not exist, shall i create it for you [y/N]? " do_create
-    case "$do_create" in
-	y|Y)
-	    if ! mkdir -p "$scratch_dir" ; then
-		log "E: could not create directory!"
-		exit 1
-	    fi
-	    ;;
-	*)
-	    log "bye."
-	    exit 0
-	    ;;
-    esac
-fi
-
-if [ ! -d "${scratch_dir}" -o ! -w "${scratch_dir}" ] ; then
-    log "scratch-dir ${scratch_dir} still does not exist or cannot be written do, giving up" >&2
+if ! sanity_check_directories ; then
+    log "E: directory check failed!"
     exit 1
-fi
-
-if [ ! -d "$log_dir" ] ; then
-    mkdir -p "$log_dir"
 fi
 
 export SDPA_SCRATCH_DIR="$scratch_dir"
@@ -305,7 +324,7 @@ export SDPA_TEMP_DIR="$temp_dir"
 # sanity check for node file
 if [ -z "$node_file" ] ; then
     log "W: node_file is not defined, please enter it now or export PBS_NODEFILE."
-    read -p "type in node file to use: " node_file
+    read -e -p "type in the node file to use: " node_file
     node_file=$( eval echo "$node_file" )
 fi
 
@@ -346,17 +365,16 @@ if [ -z "$job_id" ] ; then
 fi
 
 master="$node_name"
-TABLE="$HOME/.init-screen.tab"
-if [ -r "$TABLE" ]; then
-    if grep -q "$master" "$TABLE"; then
+if [ -r "${tab_file}" ]; then
+    if grep -q "$master" "${tab_file}"; then
 	log "# It seems, that there is already another screen environment running."
 	log "#"
 	log "# hint:"
-	log "#   possibly running on: `cat ${TABLE} | awk '{print $3}'`"
+	log "#   possibly running on: `cat ${tab_file} | awk '{print $3}'`"
 	read -n 1 -p "Do you want me to fix this? [y/N] " ignore_running
 	case $ignore_running in
 	    y|Y)
-		/bin/rm -f "${TABLE}"
+		/bin/rm -f "${tab_file}"
 		;;
 	    *)
 		exit 0
@@ -367,11 +385,9 @@ fi
 
 tmp=`cat $node_file | grep -v "$master" | uniq`
 tmp=`echo $master $tmp`
-echo "${job_id} = $tmp" > "${TABLE}"
+echo "${job_id} = $tmp" > "${tab_file}"
 
-env_file="$HOME/.init-screen.env"
-
-log "clearing .init-screen.env..."
+log "clearing ${env_file}..."
 /bin/rm -f "$env_file"
 log "writing environment info to $env_file..."
 
@@ -428,14 +444,18 @@ function open_screen_window ()
     title="${1:?}"
     node="${2:?}"
     log "opening screen window $title on node $node"
-    ssh -Y -t "$head_node" screen -D -RR -r -X "screen -t $title ssh -Y -t $node"
+    screen_opts="-D -RR -r"
+    if [ -n "$screen_name" ] ; then
+	screen_opts="$screen_opts -S $screen_name"
+    fi
+    ssh -Y -t "$head_node" screen $screen_opts -X "screen -t $title ssh -Y -t $node"
 }
 
 # fix permissions on ~/.Xauthority?
 touch $HOME/.Xauthority
 chmod u=rw,g=,o= $HOME/.Xauthority
 
-for t in log kvs gpi orch agg sdpac ; do
+for t in log sdpa ; do
     open_screen_window "$t" "$master"
 done
 open_screen_window "master:$master" "$master"
@@ -443,7 +463,7 @@ open_screen_window "master:$master" "$master"
 log "using slave nodes from ${node_file}..."
 nodes=`cat ${node_file} | grep -v "$master" | uniq`
 num_nodes=`echo $nodes | wc -w`
-max_nodes=${SDPA_MAX_SCREEN_NODES:=16}
+max_nodes=${SDPA_MAX_SCREEN_NODES:=8}
 
 open_slave_screens=true
 if [ $num_nodes -gt $max_nodes ] ; then
@@ -478,6 +498,5 @@ fi
 
 echo "# entering new shell, please logout twice from this window"
 # use the sideeffect that it will source the init-screen.env
-# you have to logout twice now ;-(
 trap "init-screen -C" EXIT
 $SHELL
