restart: start only after successful stop
From: Alexander Petry <alexander.petry@itwm.fraunhofer.de>

git-svn-id: https://svn.itwm.fhg.de/svn/SDPA@5337 c3adf61f-8968-0410-94d0-83abfdf586cf

diff --git a/trunk/sdpa/trunk/bin/pbs/sdpa b/trunk/sdpa/trunk/bin/pbs/sdpa
--- a/trunk/sdpa/trunk/bin/pbs/sdpa
+++ b/trunk/sdpa/trunk/bin/pbs/sdpa
@@ -560,8 +560,11 @@ case "$1" in
 	;;
     restart)
 	shift
-	stop $@
-	start $@
+	if stop $@ ; then
+	    start $@
+	else
+	    echo "E: stop failed, not starting!" >&2
+	fi
 	;;
     status)
 	shift
