catching error output of remote executions
From: Alexander Petry <alexander.petry@itwm.fraunhofer.de>

git-svn-id: https://svn.itwm.fhg.de/svn/SDPA@5623 c3adf61f-8968-0410-94d0-83abfdf586cf

diff --git a/trunk/sdpa/trunk/bin/pbs/sdpa b/trunk/sdpa/trunk/bin/pbs/sdpa
--- a/trunk/sdpa/trunk/bin/pbs/sdpa
+++ b/trunk/sdpa/trunk/bin/pbs/sdpa
@@ -902,9 +902,10 @@ function send_signal_to_pc ()
     local node=$1 ; shift
     local rank=$1 ; shift
     local sig=$1 ; shift
-    echo "$SDPA_HOME/bin/send-signal" -n "nre-pcd" -s "$sig" | ssh -T -x "$node" 2>&1
-    if [ $? -ne 0 ] ; then
-	echo "could not send signal $sig to pc on node $node" >&2
+    local err=$(echo "$SDPA_HOME/bin/send-signal" -n "nre-pcd" -s "$sig" | ssh -T -x "$node" 2>&1)
+    ec=$?
+    if [ $ec -ne 0 ] ; then
+	echo "could not send signal $sig to pc on node $node: $err" >&2
 	return 1
     else
 	return 0
@@ -924,9 +925,9 @@ function start_pc_on_node ()
     local rank=$1 ; shift
 
     rm -f "$SDPA_LOG_DIR/pc.$node.log"
-    echo "$SDPA_HOME/bin/start-pc" -D -r $rank $@ | ssh -T -x "$node" >/dev/null 2>&1
+    local err=$(echo "$SDPA_HOME/bin/start-pc" -D -r $rank $@ | ssh -T -x "$node" 2>&1)
     if [ $? -ne 0 ] ; then
-	echo "pc did not startup on node $node: $output" >&2
+	log "E: pc did not startup on node $node: $err" >&2
 	return 1
     else
 	return 0
@@ -946,9 +947,9 @@ function start_nre_on_node ()
     local rank=$1 ; shift
 
     rm -f "$SDPA_LOG_DIR/nre.$node.log"
-    echo "$SDPA_HOME/bin/start-nre" -D $@ | ssh -T -x "$node" >/dev/null 2>&1
+    local err=$(echo "$SDPA_HOME/bin/start-nre" -D $@ | ssh -T -x "$node" 2>&1)
     if [ $? -ne 0 ] ; then
-	echo "nre did not startup on node $node: $output" >&2
+	log "E: nre did not startup on node $node: $err" >&2
 	return 1
     else
 	return 0
@@ -959,9 +960,9 @@ function stop_pc_on_node ()
 {
     local node=$1 ; shift
     local rank=$1 ; shift
-    local err=$(echo "$SDPA_HOME/bin/stop-pc" | ssh -T -x $node >/dev/null)
+    local err=$(echo "$SDPA_HOME/bin/stop-pc" | ssh -T -x $node 2>&1)
     local ec=$?
-    if [ -n "$err" ] ; then
+    if [ $ec -ne 0 ] ; then
 	log "W: stop-pc on node $node: $err"
     fi
     return $ec
@@ -977,9 +978,9 @@ function stop_nre_on_node ()
 {
     local node=$1 ; shift
     local rank=$1 ; shift
-    local err=$(echo "$SDPA_HOME/bin/stop-nre" | ssh -T -x $node >/dev/null)
+    local err=$(echo "$SDPA_HOME/bin/stop-nre" | ssh -T -x $node 2>&1)
     local ec=$?
-    if [ -n "$err" ] ; then
+    if [ $ec -ne 0 ] ; then
 	log "W: stop-nre on node $node: $err"
     fi
     return $ec
