startup routines modified for: agent and drts
git-svn-id: https://svn.itwm.fhg.de/svn/SDPA@7045 c3adf61f-8968-0410-94d0-83abfdf586cf

diff --git a/trunk/sdpa/trunk/bin/pbs/sdpa b/trunk/sdpa/trunk/bin/pbs/sdpa
--- a/trunk/sdpa/trunk/bin/pbs/sdpa
+++ b/trunk/sdpa/trunk/bin/pbs/sdpa
@@ -10,11 +10,43 @@ config_file=${SDPA_CONFIG:="$HOME/.sdpa/configs/sdpa.rc"}
 state_dir=${SDPA_STATE_DIR:="$HOME/.sdpa/state"}
 debug_enabled=false
 
+if [ -z "$SDPA_HOME" ] ; then
+    export SDPA_HOME=$(dirname $(dirname $(which "$0")))
+fi
+
 ##############################################
 #                                            #
 #  F U N C T I O N    D E F I N I T I O N S  #
 #                                            #
 ##############################################
+
+function require()
+{
+    local tool="$1"; shift
+    if [ -z "$tool" ] ; then
+	return 2
+    fi
+
+    tool_bin=$(which "$tool" 2>/dev/null)
+    if [ -z "$tool_bin" ] ; then
+	tool_bin="$SDPA_HOME/bin/$tool"
+    fi
+
+    if [ ! -x "$tool_bin" ] ; then
+	echo "Could not locate required tool $tool" >&2
+	return 1
+    fi
+    eval "$tool=$tool_bin"
+    return 0
+}
+
+if ! require fhgcfg ; then
+    exit 1
+fi
+
+if ! require fhglogc ; then
+    exit 1
+fi
 
 function log_helper ()
 {
@@ -23,7 +55,9 @@ function log_helper ()
     local file="$0"
 
     echo "$file:$ln - $@" >&2
-    $SDPA_HOME/bin/fhglogc -L "$ln" -F "$file" -p 2 -m "$@"
+    if [ -n "$fhglogc" ] ; then
+	${fhglogc} -L "$ln" -F "$file" -p 2 -m "$@"
+    fi
 }
 
 do_log="eval log_helper \"\$FUNCNAME\" \"\$LINENO\""
@@ -45,7 +79,7 @@ function get ()
     local key="$1"; shift
     local def="$1"; shift
 
-    fhgcfg -f "$config_file" -g "$key" -v "$def"
+    ${fhgcfg} -f "$config_file" -g "$key" -v "$def"
 }
 
 function put ()
@@ -53,7 +87,7 @@ function put ()
     local key="$1"; shift
     local val="$1"; shift
 
-    fhgcfg -f "$config_file" -a "$key" -v "$val"
+    ${fhgcfg} -f "$config_file" -a "$key" -v "$val"
     log "-: set $key to '$val'"
 }
 
@@ -62,7 +96,7 @@ function rexec ()
     local node="$1"; shift
     local err
     local rc
-    local ssh_opts="-q -x -tt -n -C -4 -c arcfour,blowfish-cbc -o CheckHostIP=no -o StrictHostKeyChecking=no"
+    local ssh_opts="-q -x -T -n -C -4 -c arcfour,blowfish-cbc -o CheckHostIP=no -o StrictHostKeyChecking=no"
     local cmd="ssh $ssh_opts $node $@"
     debug $cmd
     err=$($cmd 2>&1)
@@ -723,7 +757,7 @@ function generate_environment ()
 
     # read variables from config and write them to an environment file
     #     replacing init-screen.env in principle
-    fhgcfg -f "$config_file" -l | while read key dummy val ; do
+    ${fhgcfg} -f "$config_file" -l | while read key dummy val ; do
 	case "$key" in
 	    log.server.level)
 		echo export FHGLOG_level="$val"
@@ -786,6 +820,7 @@ function generate_environment ()
     prepend_to_path LD_LIBRARY_PATH "$HOME/.sdpa/plugins"
 
     prepend_to_path PC_LIBRARY_PATH "$SDPA_HOME/libexec"
+    prepend_to_path PC_LIBRARY_PATH "$SDPA_HOME/.sdpa/modules"
 
     for f in $( find "$SDPA_LIBEXEC/apps" "$HOME/.sdpa/modules" -type f -name "*.so" ) ; do
 	mod_dir=$(dirname "$f")
@@ -800,7 +835,7 @@ function generate_environment ()
 
 function dump_config ()
 {
-    fhgcfg -f "$config_file" -p
+    ${fhgcfg} -f "$config_file" -p
 }
 
 function initialize ()
@@ -962,9 +997,7 @@ function start_proc ()
     local pid_file="$state_dir/$name.pid"
     local log_file="$SDPA_LOG_DIR/$name.log"
     local pid=$( cat "$pid_file" 2>/dev/null )
-    if is_proc_alive "$name" "$pid" ; then
-	echo "* $name ($pid)" >&2
-    else
+    if ! is_proc_alive "$name" "$pid" ; then
 	:> "$pid_file"
 	debug $binary $@
 	$binary $@ </dev/null >"$log_file" 2>&1 &
@@ -981,6 +1014,7 @@ function start_proc ()
 	echo "- $name (dead)" >&2
 	return 1
     fi
+    return 0
 }
 
 function stop_proc ()
@@ -1035,13 +1069,16 @@ function start_agent ()
 	node=localhost
     fi
 
-    err=$(rexec "$node" -T "$SDPA_HOME/bin/start-agent" -D -n "$name" -m "$master" -f $@ 2>&1)
-    if [ $? -eq 0 ] ; then
+    err=$(rexec "$node" "$SDPA_HOME/bin/start-agent" -D -n "$name" -m "$master" $@ </dev/null 2>&1)
+    ec=$?
+    if [ $ec -eq 0 ] ; then
 	echo "+ $name" >&2
 	return 0
+    elif [ $ec -eq 2 ] ; then
+	return 0
     else
-	echo "- $name: $err" >&2
-	return 1
+	echo "- $name: $ec: $err" >&2
+	return $ec
     fi
 }
 
@@ -1086,7 +1123,7 @@ function start_kvs ()
 
 function stop_kvs ()
 {
-    echo "* fhgkvsd"
+    echo "fhgkvsd"
     if ! stop_proc "fhgkvsd" "fhgkvsd" ; then
 	echo "E: could not stop kvs!" >&2
 	return 1
@@ -1105,7 +1142,7 @@ function start_orch ()
 
 function stop_orch ()
 {
-    echo "* orchestrator"
+    echo "orchestrator"
     if ! stop_proc "orchestrator" "start-orch" ; then
 	echo "E: could not stop orchestrator" >&2
 	return 1
@@ -1124,7 +1161,7 @@ function start_agg ()
 
 function stop_agg ()
 {
-    echo "* aggregator"
+    echo "aggregator"
     if ! stop_agent "aggregator" ; then
 	echo "E: could not stop aggregator" >&2
 	return 1
@@ -1207,22 +1244,17 @@ function start_nre ()
 {
     local with_mediator=$(get "topology.with-mediator" "true")
     if [ x"$with_mediator" == x"true" ] ; then
-	log "* nres" >&2
+	log "nres" >&2
 	node_loop start_nre_on_node $@
     else
-	log "* nres (deactivated)" >&2
+	log "nres (deactivated)" >&2
     fi
 }
 
 function stop_nre ()
 {
-    log "* nres" >&2
-#    local with_mediator=$(get "topology.with-mediator" "true")
-#    if [ x"$with_mediator" == x"true" ] ; then
+    log "nres" >&2
     node_loop stop_nre_on_node $@
-#    else
-#	log "      * deactivated" >&2
-#    fi
 }
 
 function status_nre ()
@@ -1230,12 +1262,12 @@ function status_nre ()
     local err
     local ec
 
-    local with_mediator=$(get "topology.with-mediator" "true")
+    with_mediator=$(get "topology.with-mediator" "true")
     if [ x"$with_mediator" == x"true" ] ; then
 	err=$(node_loop status_nre_on_node $@ 2>&1)
 	ec=$?
     else
-	ec=255
+	ec=23
     fi
     return $ec
 }
@@ -1276,7 +1308,7 @@ function status_nre_on_node ()
 function start_drts ()
 {
     local node=
-    local master=
+    local master=aggregator
     local ident=
     local count=
 
@@ -1310,7 +1342,7 @@ function start_drts ()
     done
 
     if [ -z "$node" ] ; then
-	echo "* process container (all nodes)" >&2
+	echo "process container (all nodes)" >&2
 	err=$(node_loop start_drts_on_node 2>&1)
 	ec=$?
 	if [ $ec -ne 0 ] ; then
@@ -1319,14 +1351,14 @@ function start_drts ()
 	fi
     else
 	if [ -z "$ident" ] ; then
-	    echo "* process container $node" >&2
-	    start_drts_on_node "$node" "$master" "$count" -i "0" &
+	    echo "process container $node" >&2
+	    start_drts_on_node "$node" "$master" "$count" &
 	    wait $(jobs -p)
 	    ec=$?
 	    return $ec
 	else
 	    count=1
-	    echo "* process container $node-$ident" >&2
+	    echo "process container $node-$ident with master $master" >&2
 	    start_drts_on_node "$node" "$master" "$count" -i "$ident" 2>&1 &
 	    wait $(jobs -p)
 	    ec=$?
@@ -1362,7 +1394,7 @@ function stop_drts ()
     done
 
     if [ -z "$node" ] ; then
-	echo "* process container (all nodes)" >&2
+	echo "process container (all nodes)" >&2
 	err=$(node_loop stop_drts_on_node 2>&1)
 	ec=$?
 	if [ $ec -ne 0 ] ; then
@@ -1371,11 +1403,17 @@ function stop_drts ()
 	fi
     else
 	if [ -z "$ident" ] ; then
-	    echo "* process container $node" >&2
-	    stop_drts_on_node "$node"
+	    echo "process container $node" >&2
+	    stop_drts_on_node "$node" &
+	    wait $(jobs -p)
+	    ec=$?
+	    return $ec
 	else
-	    echo "* process container $node-$ident" >&2
-	    stop_drts_on_node "$node" -i "$ident"
+	    echo "process container $node-$ident" >&2
+	    stop_drts_on_node "$node" -i "$ident" 2>&1 &
+	    wait $(jobs -p)
+	    ec=$?
+	    return $ec
 	fi
     fi
 }
@@ -1404,7 +1442,7 @@ function start_drts_on_node ()
 	per_node=$(get "topology.per-node" "0")
     fi
 
-    local with_mediator=$(get "topology.with-mediator" "true")
+    with_mediator=$(get "topology.with-mediator" "true")
     if [ x"$with_mediator" == x"true" ] ; then
 	master="nre-$node"
     fi
@@ -1488,13 +1526,13 @@ function start_gpi ()
 	    return 0
 	fi
     else
-	log "* gpi (deactivated)" >&2
+	log "gpi (deactivated)" >&2
     fi
 }
 
 function stop_gpi ()
 {
-    log "* gpi"
+    log "gpi"
     if ! stop_proc "gpi-space" "gpi-space" ; then
 	log "E: could not stop gpi"
 	return 1
@@ -1515,16 +1553,16 @@ function start ()
     local p
     local rc=0
     for p in $parts ; do
-	status_$p $@ >/dev/null 2>&1
-	if [ $? -eq 0 ] ; then
-	    log "* $p"
-	    continue
-	fi
-
+#
+#	status_$p $@ >/dev/null 2>&1
+#	if [ $? -eq 0 ] ; then
+#	    log "$p still running"
+#	    continue
+#	fi
 	if ! start_$p $@ ; then
 	    log "Start of $p failed!"
 	    rc=$(( rc + 1 ))
-	    break
+#	    break
 	fi
     done
     return $rc
@@ -1596,7 +1634,7 @@ function status_gpi ()
 	program_status "gpi-space"
 	ec=$?
     else
-	ec=255
+	ec=23
     fi
     return $ec
 }
@@ -1622,7 +1660,7 @@ function status ()
 	    ec=$?
 	    if [ $ec -eq 0 ] ; then
 		log "$p is alive"
-	    elif [ $ec -eq 255 ] ; then
+	    elif [ $ec -eq 23 ] ; then
 		log "$p is deactivated"
 	    else
 		if [ -z "$err" ] ; then
