added selftest command to the sdpa script

diff --git a/trunk/sdpa/trunk/bin/pbs/sdpa b/trunk/sdpa/trunk/bin/pbs/sdpa
--- a/trunk/sdpa/trunk/bin/pbs/sdpa
+++ b/trunk/sdpa/trunk/bin/pbs/sdpa
@@ -1037,6 +1037,16 @@ function stop ()
     return $rc
 }
 
+function restart ()
+{
+    if stop $@ ; then
+	start $@
+    else
+	echo "E: stop failed, not starting!" >&2
+	return 1
+    fi
+}
+
 function program_status ()
 {
     local p=$1 ; shift
@@ -1226,6 +1236,12 @@ function on_valid_host ()
 {
     local host="$(hostname -s)"
     if test -r "$state_dir/nodefile" ; then
+	if [ -n "$PBS_NODEFILE" ] ; then
+	    if ! diff -q "$PBS_NODEFILE" "$state_dir/nodefile" >/dev/null ; then
+		log "E: $PBS_NODEFILE and $state_dir/nodefile differ"
+		return 1
+	    fi
+	fi
 	if grep -q -e "$host" "$state_dir/nodefile" ; then
 	    return 0
 	else
@@ -1249,6 +1265,103 @@ function on_master_node ()
 	log "E: no nodefile present"
     fi
     return 1
+}
+
+function selftest ()
+{
+    log "I: performing self-test"
+
+    local xml="$SDPA_HOME/share/sdpa/examples/selftest/selftest.xml"
+    if ! test -r "$xml" ; then
+	log "E: cannot read $xml"
+	return 1
+    fi
+
+    local pnetc=$(which pnetc)
+    if ! test -x "$pnetc" ; then
+	log "E: cannot execute $pnetc"
+	return 2
+    fi
+
+    local sdpac=$(which sdpac)
+    if ! test -x "$sdpac" ; then
+	log "E: cannot execute sdpac"
+	return 3
+    fi
+
+    local pnetget=$(which pnetget)
+    if ! test -x "$pnetget" ; then
+	log "E: cannot execute pnetget"
+	return 3
+    fi
+
+    if ! restart ; then
+	stop
+	log "E: restart failed"
+	return 4
+    fi
+
+    local job_desc=$(mktemp)
+    local old_trap=$(trap -p EXIT)
+    trap -- "rm -f $job_desc" EXIT
+
+    log "I: building job description..."
+    if ! $pnetc "$xml" > "$job_desc" ; then
+	log "E: could not generate job description"
+	return 5
+    fi
+
+    log "I: submitting job..."
+    local job_id=$(sdpac submit "$job_desc")
+    log "I: JOB-ID: $job_id"
+
+    local walltime=120
+    log "I: waiting at most $walltime seconds for job to return..."
+    local job_state=42
+    for ((i=0 ; i < $walltime ; ++i)) ; do
+	sleep 1
+	local job_status=$(sdpac status "$job_id")
+	if echo "$job_status" | grep -q -i -e 'finished' ; then
+	    log "I: job has finished"
+	    job_state=0
+	    break
+	elif echo "$job_status" | grep -q -i -e 'failed' ; then
+	    log "E: job has failed"
+	    job_state=1
+	    break
+	elif echo "$job_status" | grep -q -i -e 'cancelled' ; then
+	    log "E: job has been cancelled"
+	    job_state=2
+	    break
+	fi
+    done
+
+    if [ "$job_state" -eq 0 ] ; then
+	log "I: retrieving results"
+	if ! sdpac --force -o "$job_desc" results "$job_id" ; then
+	    log "E: could not retrieve results"
+	    rm "$job_desc"
+	    stop
+	    return 6
+	fi
+
+	if ! sdpac delete "$job_id" ; then
+	    log "E: could not delete job"
+	    rm "$job_desc"
+	    stop
+	    return 7
+	fi
+	local tokens=$(pnetget -i "$job_desc")
+	log "I: result tokens: $tokens"
+    else
+	log "E: self test job could not be executed!"
+	return 8
+    fi
+
+    rm "$job_desc"
+    stop
+
+    return 0
 }
 
 ##########################################################
@@ -1310,11 +1423,7 @@ case "$1" in
 	    exit 1
 	fi
 	shift
-	if stop $@ ; then
-	    start $@
-	else
-	    echo "E: stop failed, not starting!" >&2
-	fi
+	restart $@
 	;;
     status)
 	if ! on_master_node ; then
@@ -1357,6 +1466,13 @@ case "$1" in
 	if test -f "$state_dir/sdpa.env" ; then
 	    echo source "$state_dir/sdpa.env"\;
 	fi
+	;;
+    selftest)
+	if ! on_master_node ; then
+	    log "E: not on master node"
+	    exit 1
+	fi
+	selftest
 	;;
     '')
 	help
