Merge branch 'devel'
git-svn-id: https://svn.itwm.fhg.de/svn/SDPA@7047 c3adf61f-8968-0410-94d0-83abfdf586cf

diff --git a/trunk/sdpa/trunk/bin/pbs/sdpa b/trunk/sdpa/trunk/bin/pbs/sdpa
--- a/trunk/sdpa/trunk/bin/pbs/sdpa
+++ b/trunk/sdpa/trunk/bin/pbs/sdpa
@@ -101,12 +101,14 @@ function rexec ()
     debug $cmd
     err=$($cmd 2>&1)
     rc=$?
-    if [ $rc -ne 0 ] ; then
-	echo $err >&2
+    if [ $rc -eq 0 ] ; then
+	return 0
+    elif [ $rc -eq 255 ] ; then
+	echo "ssh could not connect to $node: $err: $rc" >&2
 	return $rc
     else
 	echo $err
-	return 0
+	return $rc
     fi
 }
 
