printing error message when start gui failed
From: Alexander Petry <alexander.petry@itwm.fraunhofer.de>

git-svn-id: https://svn.itwm.fhg.de/svn/SDPA@6862 c3adf61f-8968-0410-94d0-83abfdf586cf

diff --git a/trunk/sdpa/trunk/bin/pbs/start-gui b/trunk/sdpa/trunk/bin/pbs/start-gui
--- a/trunk/sdpa/trunk/bin/pbs/start-gui
+++ b/trunk/sdpa/trunk/bin/pbs/start-gui
@@ -3,4 +3,9 @@
 test -r "$HOME/.sdpa/state/sdpa.env" && source "$HOME/.sdpa/state/sdpa.env"
 
 log "Running sdpa-gui $@ on $(hostname)"
-sdpa-gui $@ 2>/dev/null
+err=$(sdpa-gui $@ 2>&1)
+ec=$?
+if [ $ec -ne 0 ] ; then
+	echo "sdpa-gui failed: $ec: $err" >&2
+	exit $ec
+fi
