checking for SDPA_LOG_DIR and SDPA_GPI_CFG variables
From: Alexander Petry <alexander.petry@itwm.fraunhofer.de>

git-svn-id: https://svn.itwm.fhg.de/svn/SDPA@4015 c3adf61f-8968-0410-94d0-83abfdf586cf

diff --git a/trunk/sdpa/trunk/bin/pbs/start-nre b/trunk/sdpa/trunk/bin/pbs/start-nre
--- a/trunk/sdpa/trunk/bin/pbs/start-nre
+++ b/trunk/sdpa/trunk/bin/pbs/start-nre
@@ -15,14 +15,36 @@ then
   gui_url="lts019.itwm.fhg.de:9001"
 fi
 
+if [ -z "$SDPA_LOG_DIR" ] ; then
+  echo "# SDPA_LOG_DIR is not set!"
+  exit 1
+fi
+
+if [ ! -w "$SDPA_LOG_DIR" ] ; then
+  echo "# SDPA_LOG_DIR=\"$SDPA_LOG_DIR\" is not writable!"
+  exit 1
+fi
+
 rank=0
 if [ -n "$1" ]; then
   rank=$1
 fi
 
-fvm_pc_cfg="/p/herc/itwm/hpc/soft/sdpa/fvm-pc/etc/fvm.cfg"
-if [ -n "$SDPA_FVM_PC_CFG" ]; then
-  fvm_pc_cfg="$SDPA_FVM_PC_CFG"
+gpi_cfg=
+if [ -n "$SDPA_GPI_CFG" -a -r "$SDPA_GPI_CFG" ] ; then
+  gpi_cfg="$SDPA_GPI_CFG"
+elif [ -r "$HOME/.sdpa/configs/gpi.rc" ] ; then
+  gpi_cfg="$HOME/.sdpa/configs/gpi.rc"
+elif [ -n "$SDPA_GPI_CFG" -a -r "$SDPA_HOME/etc/gpi/sdpa-gpi.cfg" ] ; then
+  gpi_cfg="$SDPA_HOME/etc/gpi/sdpa-gpi.cfg"
+else
+  echo "# could not figure out, which config file to use!"
+  echo "#    the following might help:"
+  echo "#"
+  echo "#       set SDPA_GPI_CFG (current: $SDPA_GPI_CFG)"
+  echo "#       create \$HOME/.sdpa/configs/gpi.rc"
+  echo "#       create \$SDPA_HOME/etc/gpi/sdpa-gpi.cfg"
+  exit 1
 fi
 
 while read k v; do
@@ -44,7 +66,7 @@ while read k v; do
 	    export FVM_PC_SHM="$v"
 	    ;;
     esac
-done < "$fvm_pc_cfg"
+done < "$gpi_cfg"
 
 log "killing process-container..."
 killall nre-pcd >/dev/null 2>&1
