start-gpi has a 'force' switch now
  - forces automatic copy of a new gpi binary if necessary
  - binaries are compared using md5sum in addition to timestamps

From: Alexander Petry <alexander.petry@itwm.fraunhofer.de>

git-svn-id: https://svn.itwm.fhg.de/svn/SDPA@4504 c3adf61f-8968-0410-94d0-83abfdf586cf

diff --git a/trunk/sdpa/trunk/bin/pbs/start-gpi.in b/trunk/sdpa/trunk/bin/pbs/start-gpi.in
--- a/trunk/sdpa/trunk/bin/pbs/start-gpi.in
+++ b/trunk/sdpa/trunk/bin/pbs/start-gpi.in
@@ -20,6 +20,7 @@ elif [ -r "$HOME/.sdpa/configs/gpi.dir" ] ; then
 fi
 
 gpi_exe="sdpa-gpi"
+force=false
 
 function usage ()
 {
@@ -30,11 +31,15 @@ usage: $0 [options]
     -d gpid directory (=$gpi_bin_path): priviledged binary path for the gpid
     -c gpi-cfg (=$gpi_cfg): path to the gpi cfg
     -x gpi-exe (=$gpi_exe): gpi program to use
+    -f: force (always copy binary)
 EOF
 }
 
-while getopts ":hd:c:x:" opt; do
+while getopts ":hfd:c:x:" opt; do
     case $opt in
+	f)
+	    force=true
+	    ;;
 	d)
 	    gpi_bin_path=$OPTARG
 	    ;;
@@ -62,47 +67,57 @@ if [ -z "$gpi_bin_path" ] ; then
 fi
 
 gpi_exe_path="$( which ${gpi_exe} 2>/dev/null )"
-if [ ! -x "${gpi_exe_path}" ] ; then
+if [ ! -f "${gpi_exe_path}" -a ! -x "${gpi_exe_path}" ] ; then
   log "Sorry, no ${gpi_exe} binary found in PATH"
   exit 1
 fi
 gpi_exe="$(basename ${gpi_exe_path})"
 
-ask_copy=false
+need_copy=false
 if [ ! -x "${gpi_bin_path}/${gpi_exe}" ] ; then
    log "${gpi_exe} does not seem to be installed in $gpi_bin_path"
-   ask_copy=true
+   need_copy=true
 else
     ts_inst=$( stat -c %Y "${gpi_bin_path}/${gpi_exe}" )
     ts_cand=$( stat -c %Y "${gpi_exe_path}" )
     if [ $ts_cand -gt $ts_inst ] ; then
-	log "candidate ${gpi_exe_path} is newer than the one in ${gpi_bin_path}"
-	ask_copy=true
+	md_inst=$( md5sum "${gpi_bin_path}/${gpi_exe}" | cut -d ' ' -f 1 )
+	md_cand=$( md5sum "${gpi_exe_path}" | cut -d ' ' -f 1 )
+	if [ "$md_inst" != "$md_cand" ] ; then
+	    log "candidate ${gpi_exe_path} is newer than the one in ${gpi_bin_path}"
+	    need_copy=true
+	fi
     fi
 fi
 
-if [ $ask_copy == "true" ] ; then
-    read -t 60 -n 1 -p "Do you want me to copy \"$gpi_exe_path\" to \"$gpi_bin_path\"? [y/N] " install_gpi
-    echo
-    case "$install_gpi" in
+do_copy=false
+if [ $need_copy == "true" -a $force == "true" ] ; then
+    do_copy=true
+fi
+if [ $need_copy == "true" -a $do_copy == "false" ] ; then
+    read -t 5 -n 1 -p "Do you want me to copy \"$gpi_exe_path\" to \"$gpi_bin_path\"? [y/N] " ans
+    case "$ans" in
 	y|Y)
-	    if [ ! -d "$gpi_bin_path" ] ; then
-		tmp=$( mkdir -p "$gpi_bin_path" 2>&1 )
-		if [ $? -ne 0 ] ; then
-		    log "could not create $gpi_bin_path: $tmp"
-		    exit 1
-		fi
-	    fi
-
-	    if [ -w "$gpi_bin_path" ] ; then
-		cp "${gpi_exe_path}" "${gpi_bin_path}/${gpi_exe}"
-	    else
-		log "$gpi_bin_path does not exist, or i am not allowed to write to it!"
-	    fi
+	    do_copy=true
 	    ;;
 	*)
 	    ;;
     esac
+fi
+
+if [ $do_copy == "true" ] ; then
+    if [ ! -d "$gpi_bin_path" ] ; then
+	tmp=$( mkdir -p "$gpi_bin_path" 2>&1 )
+	if [ $? -ne 0 ] ; then
+	    log "could not create $gpi_bin_path: $tmp"
+	    exit 1
+	fi
+    fi
+    if [ -w "$gpi_bin_path" ] ; then
+	cp "${gpi_exe_path}" "${gpi_bin_path}/${gpi_exe}"
+    else
+	log "$gpi_bin_path does not exist, or i am not allowed to write to it!"
+    fi
 fi
 
 if [ -x "$gpi_bin_path/$gpi_exe" ] ; then
