status nre does not rely on PBS_NODEFILE anymore...
From: Alexander Petry <alexander.petry@itwm.fraunhofer.de>

git-svn-id: https://svn.itwm.fhg.de/svn/SDPA@4022 c3adf61f-8968-0410-94d0-83abfdf586cf

diff --git a/trunk/sdpa/trunk/bin/pbs/status-nre b/trunk/sdpa/trunk/bin/pbs/status-nre
--- a/trunk/sdpa/trunk/bin/pbs/status-nre
+++ b/trunk/sdpa/trunk/bin/pbs/status-nre
@@ -1,11 +1,13 @@
 #!/bin/sh
 
-if [ ! -r "$PBS_NODEFILE" ]; then
-  echo "E: must be run on head node"
-  exit 123
+source ~/.init-screen.env
+
+if [ ! -r "$SDPA_NODEFILE" ]; then
+    log "I cannot access the nodefile: $SDPA_NODEFILE"
+    exit 2
 fi
 
-node_max=$( uniq $PBS_NODEFILE | wc -l )
+node_max=$( uniq $SDPA_NODEFILE | wc -l )
 nodes=$( echo $( seq 1 $node_max ) )
 if [ $# -lt 1 ]; then
   echo "checking all NREs..."
@@ -21,7 +23,7 @@ for node_num in $nodes; do
   fi
 
   nre_ec=0
-  node_name=$( uniq $PBS_NODEFILE | tail -n +$node_num | head -n 1 )
+  node_name=$( uniq $SDPA_NODEFILE | tail -n +$node_num | head -n 1 )
   echo -n "checking status of nre on $node_name..."
   ssh -x $node_name ps aux | grep -q '[n]re-pc' >/dev/null 2>&1
   if [ $? -eq 0 ]; then
