filter: added support for pipelines
From: Alexander Petry <alexander.petry@itwm.fraunhofer.de>

git-svn-id: https://svn.itwm.fhg.de/svn/SDPA@3853 c3adf61f-8968-0410-94d0-83abfdf586cf

diff --git a/trunk/application/example/filter/parallel b/trunk/application/example/filter/parallel
--- a/trunk/application/example/filter/parallel
+++ b/trunk/application/example/filter/parallel
@@ -20,6 +20,11 @@ outt=${4:?}
 prog=${5:?}
 shift 5
 
+if [ ! -r "$inf" ] ; then
+  echo "E: cannot access $inf for reading, aborting"
+  exit 1
+fi
+
 if [ -r "$tune_cfg" ] ; then
   cat "$tune_cfg" > "$filter_cfg"
 else
@@ -46,13 +51,35 @@ abs_inf="$REPLY"
 abspath ${outf}
 abs_outf="$REPLY"
 
+# create the shell script to execute the filter
+script=$( mktemp -p "$filter_dir" filter.sh.XXXXXX )
+if [ $? -ne 0 ] ; then
+  echo "could not create temporary file in $filter_dir"
+  exit 2
+fi
+
+cat > "$script" <<EOF
+#!/bin/bash
+$prog $@
+EOF
+chmod +x "${script}"
+
 cat >> "$filter_cfg" <<EOF
 input.file ${abs_inf}
 input.type ${int}
 output.file ${abs_outf}
 output.type ${outt}
-exec.su "${prog} $@"
+exec.su "${script}"
 EOF
+
+cleanup ()
+{
+  rm -f "${script}"
+}
+trap cleanup EXIT
+
+echo "generated script file:"
+cat "${script}"
 
 echo "generating job description..."
 sed -e "s,@CONFIG_FILE@,$filter_cfg," "$filter_dir/loop.xml.in" > "$filter_dir/loop.xml"
@@ -68,3 +95,4 @@ if [ $? -ne 0 ] ; then
 fi
 
 sdpac -w submit $filter_dir/su4.pnet
+test -e "${script}" && rm -f "${script}"
