su pipes are possible now
From: Alexander Petry <alexander.petry@itwm.fraunhofer.de>

git-svn-id: https://svn.itwm.fhg.de/svn/SDPA@5575 c3adf61f-8968-0410-94d0-83abfdf586cf

diff --git a/trunk/application/parsu/shrink/parsu_shrink.in b/trunk/application/parsu/shrink/parsu_shrink.in
--- a/trunk/application/parsu/shrink/parsu_shrink.in
+++ b/trunk/application/parsu/shrink/parsu_shrink.in
@@ -4,33 +4,21 @@ shrink_dir="@PARSU_SHRINK_DIR@"
 
 tmp_dir=${PARSU_TMP_DIR:-${TMPDIR}}
 
-if [ ! -d "${tmp_dir}" -a -w "${tmp_dir}" ] ; then
+if [ ! \( -d "${tmp_dir}" -a -w "${tmp_dir}" \) ] ; then
   echo "E: no (writeable) temp dir given (is: \"${tmp_dir}\")"
   echo "set PARSU_TMP_DIR or TMPDIR"
   exit 1
 fi
 
+scratch_dir=${PARSU_SCRATCH_DIR:-${SDPA_SCRATCH_DIR}}
+if [ ! \( -d "${scratch_dir}" -a -w "${scratch_dir}" \) ] ; then
+    echo "E: no (writable) scratch dir given (is: \"${scratch_dir}\")"
+    echo "set PARSU_SCRATCH_DIR or SDPA_SCRATCH_DIR"
+    exit 1
+fi
+
 xml_file_in="${shrink_dir}/shrink.xml.in"
 mk_xml="${shrink_dir}/mk.xml"
-
-cleanup ()
-{
-    test -e "${xml_file}"  && rm -f "${xml_file}"
-    test -e "${pnet_file}" && rm -f "${pnet_file}"
-}
-trap cleanup EXIT
-
-xml_file=$( mktemp "${tmp_dir}/parsu_shrink.xml.XXXXXX" )
-if [ $? -ne 0 ] ; then
-  echo "could not create temporary file in ${tmp_dir}" >/dev/stderr
-  exit 2
-fi
-
-pnet_file=$( mktemp "${tmp_dir}/parsu_shrink.pnet.XXXXXX" )
-if [ $? -ne 0 ] ; then
-  echo "could not create temporary file in ${tmp_dir}" >/dev/stderr
-  exit 2
-fi
 
 shmem_per_node_default=$((2**28))
 gpi_mem_per_node_default=$((2**30))
@@ -53,6 +41,33 @@ if [ ! -r "$inf" ] ; then
   exit 1
 fi
 
+cleanup ()
+{
+    test -e "${xml_file}"  && rm -f "${xml_file}"
+    test -e "${pnet_file}" && rm -f "${pnet_file}"
+    test -e "${script_file}" && rm -f "${script_file}"
+}
+trap cleanup EXIT
+
+xml_file=$( mktemp "${tmp_dir}/parsu_shrink.xml.XXXXXX" )
+if [ $? -ne 0 ] ; then
+  echo "could not create temporary file in ${tmp_dir}" >/dev/stderr
+  exit 2
+fi
+
+pnet_file=$( mktemp "${tmp_dir}/parsu_shrink.pnet.XXXXXX" )
+if [ $? -ne 0 ] ; then
+  echo "could not create temporary file in ${tmp_dir}" >/dev/stderr
+  exit 2
+fi
+
+script_file=$( mktemp "${scratch_dir}/parsu_shrink.sh.XXXXXX" )
+if [ $? -ne 0 ] ; then
+    echo "could not create temporary script in ${scratch_dir}" >&2
+    exit 2
+fi
+chmod +x "${script_file}"
+
 abspath ()
 {
   p="$1"
@@ -73,6 +88,12 @@ abs_inf="$REPLY"
 abspath ${outf}
 abs_outf="$REPLY"
 
+echo "-: generating command script..." >&2
+cat > "$script_file" <<EOF
+#!/bin/sh
+$cmd $@
+EOF
+
 echo -n "-: generating job description..." >/dev/stderr
 
 cat "${xml_file_in}" | ${mk_xml}             \
@@ -80,7 +101,7 @@ cat "${xml_file_in}" | ${mk_xml}             \
                        "${int}"              \
                        "${abs_outf}"         \
                        "${outt}"             \
-                       "${cmd}"              \
+                       "${script_file}"      \
                        "${shmem_per_node}"   \
                        "${gpi_mem_per_node}" \
                        "--BUILD--"           \
