fixed handling of default_prefix
git-svn-id: https://svn.itwm.fhg.de/svn/SDPA@6957 c3adf61f-8968-0410-94d0-83abfdf586cf

diff --git a/trunk/sdpa/trunk/etc/sdpa.env.in b/trunk/sdpa/trunk/etc/sdpa.env.in
--- a/trunk/sdpa/trunk/etc/sdpa.env.in
+++ b/trunk/sdpa/trunk/etc/sdpa.env.in
@@ -22,11 +22,13 @@ if [ -n "$SDPA_HOME" ] ; then
 else
     if [ -r "$HOME/.sdpa/home" ] ; then
 	prefix=$(cat "$HOME/.sdpa/home")
+    else
+	prefix="${default_prefix}"
     fi
 fi
 
 if [ -z "$prefix" -o ! -d "$prefix" ] ; then
-    echo "cannot access $prefix: no such directory" >&2
+    echo "cannot access \`$prefix': no such directory" >&2
     echo "please export SDPA_HOME or write the path to $HOME/.sdpa/home" >&2
 else
     if [ -z "$SDPA_LOADED" -o -n "$FORCE_LOAD_SDPA" ]; then
