pkg: chg: check for errors during install

diff --git a/installer/installer.sh.in b/installer/installer.sh.in
--- a/installer/installer.sh.in
+++ b/installer/installer.sh.in
@@ -153,7 +153,10 @@ destdir=$(abspath "${destdir}")
 
 if [ ! -d "${destdir}" ]
 then
-    mkdir -p "${destdir}"
+    mkdir -p "${destdir}" || {
+        echo >&2 "install: could not create destination directory"
+        exit 1
+    }
 fi
 dst="${destdir}/$GSPC_DIRECTORY_NAME"
 
@@ -169,7 +172,12 @@ then
 fi
 
 # uses TMPDIR as a prefix if set, otherwise /tmp
-tmpdir=$(mktemp -d gspc-installer.XXXXXXXXXX)
+tmpdir=$(mktemp --tmpdir -d "gspc-installer.XXXXXXXXXX" 2>&1)
+if [ $? -ne 0 ]
+then
+    echo >&2 "install: could not create temporary directory: $tmpdir"
+    exit 1
+fi
 
 cleanup ()
 {
@@ -194,11 +202,17 @@ fi
 info "installing..."
 
 ARCHIVE=$(awk '/^__TAR_ARCHIVE_STARTS_HERE__/ {print NR + 1; exit 0; }' "$0")
-tail -n+"$ARCHIVE" "$0" | tar xjf - -C "${tmpdir}"
+tail -n+"$ARCHIVE" "$0" | tar xjf - -C "${tmpdir}" || {
+    echo >&2 "install: could not unpack!"
+    exit 3
+}
 
 olddir="$(pwd)"
 
-mv "${tmpdir}/${GSPC_DIRECTORY_NAME}" "${dst}"
+mv "${tmpdir}/${GSPC_DIRECTORY_NAME}" "${dst}" || {
+    echo >&2 "install: could not move to '${dst}'"
+    exit 3
+}
 
 if [ -r "${license}" ]
 then
